import { ScreenDefinition } from "@/types";

// All available screens
export const screenRegistry: Record<string, ScreenDefinition> = {
  // Student screens
  "student-home": {
    screen_id: "student-home",
    name: "Student Home",
    screen_type: "dashboard",
    allowed_roles: ["student"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "study-hub": {
    screen_id: "study-hub",
    name: "Study Hub",
    screen_type: "hub",
    allowed_roles: ["student"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "schedule-screen": {
    screen_id: "schedule-screen",
    name: "Schedule",
    screen_type: "hub",
    allowed_roles: ["student", "teacher", "parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "doubts-home": {
    screen_id: "doubts-home",
    name: "Doubts",
    screen_type: "hub",
    allowed_roles: ["student", "teacher"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "progress-home": {
    screen_id: "progress-home",
    name: "Progress",
    screen_type: "hub",
    allowed_roles: ["student", "parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "profile-home": {
    screen_id: "profile-home",
    name: "Profile",
    screen_type: "hub",
    allowed_roles: ["student", "teacher", "parent", "admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: false,
    header_visible: true,
  },

  "tests-home": {
    screen_id: "tests-home",
    name: "Tests",
    screen_type: "hub",
    allowed_roles: ["student"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "assignments-home": {
    screen_id: "assignments-home",
    name: "Assignments",
    screen_type: "hub",
    allowed_roles: ["student"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "test-center": {
    screen_id: "test-center",
    name: "Test Center",
    screen_type: "hub",
    allowed_roles: ["student"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "social-home": {
    screen_id: "social-home",
    name: "Social",
    screen_type: "hub",
    allowed_roles: ["student"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },

  // Teacher screens
  "teacher-home": {
    screen_id: "teacher-home",
    name: "Teacher Home",
    screen_type: "dashboard",
    allowed_roles: ["teacher"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "classes-screen": {
    screen_id: "classes-screen",
    name: "My Classes",
    screen_type: "hub",
    allowed_roles: ["teacher"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "students-screen": {
    screen_id: "students-screen",
    name: "Students",
    screen_type: "hub",
    allowed_roles: ["teacher"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "teacher-doubts": {
    screen_id: "teacher-doubts",
    name: "Student Doubts",
    screen_type: "hub",
    allowed_roles: ["teacher"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },

  // Parent screens
  "parent-home": {
    screen_id: "parent-home",
    name: "Parent Home",
    screen_type: "dashboard",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "children-overview": {
    screen_id: "children-overview",
    name: "My Children",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "child-detail": {
    screen_id: "child-detail",
    name: "Child Detail",
    screen_type: "detail",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "child-progress-screen": {
    screen_id: "child-progress-screen",
    name: "Child Progress",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "attendance-overview": {
    screen_id: "attendance-overview",
    name: "Attendance Overview",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "child-attendance": {
    screen_id: "child-attendance",
    name: "Child Attendance",
    screen_type: "detail",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "child-progress-detail": {
    screen_id: "child-progress-detail",
    name: "Child Progress Detail",
    screen_type: "detail",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "performance-detail": {
    screen_id: "performance-detail",
    name: "Performance Detail",
    screen_type: "detail",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "child-subjects": {
    screen_id: "child-subjects",
    name: "Child Subjects",
    screen_type: "detail",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "child-report-card": {
    screen_id: "child-report-card",
    name: "Child Report Card",
    screen_type: "detail",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "child-stats-detail": {
    screen_id: "child-stats-detail",
    name: "Child Stats Detail",
    screen_type: "detail",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "child-weak-areas-detail": {
    screen_id: "child-weak-areas-detail",
    name: "Child Weak Areas Detail",
    screen_type: "detail",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "child-assignments": {
    screen_id: "child-assignments",
    name: "Child Assignments",
    screen_type: "detail",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "fees-overview": {
    screen_id: "fees-overview",
    name: "Fees Overview",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "payment-history": {
    screen_id: "payment-history",
    name: "Payment History",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },

  // Admin screens
  "admin-home": {
    screen_id: "admin-home",
    name: "Admin Dashboard",
    screen_type: "dashboard",
    allowed_roles: ["admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "admin-users": {
    screen_id: "admin-users",
    name: "User Management",
    screen_type: "hub",
    allowed_roles: ["admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "users-management": {
    screen_id: "users-management",
    name: "User Management",
    screen_type: "hub",
    allowed_roles: ["admin", "super_admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "finance-reports": {
    screen_id: "finance-reports",
    name: "Finance Reports",
    screen_type: "hub",
    allowed_roles: ["admin", "super_admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "finance-dashboard": {
    screen_id: "finance-dashboard",
    name: "Finance Dashboard",
    screen_type: "dashboard",
    allowed_roles: ["admin", "super_admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "analytics-dashboard": {
    screen_id: "analytics-dashboard",
    name: "Analytics Dashboard",
    screen_type: "dashboard",
    allowed_roles: ["admin", "super_admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "admin-analytics": {
    screen_id: "admin-analytics",
    name: "Analytics Dashboard (Dynamic)",
    screen_type: "dashboard",
    allowed_roles: ["admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "content-management": {
    screen_id: "content-management",
    name: "Content Management",
    screen_type: "hub",
    allowed_roles: ["admin", "super_admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "system-settings": {
    screen_id: "system-settings",
    name: "System Settings",
    screen_type: "hub",
    allowed_roles: ["admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "audit-logs": {
    screen_id: "audit-logs",
    name: "Audit Logs",
    screen_type: "hub",
    allowed_roles: ["admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "admin-profile": {
    screen_id: "admin-profile",
    name: "Admin Profile",
    screen_type: "profile",
    allowed_roles: ["admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: false,
    header_visible: true,
  },

  // Multi-role screens
  "notifications": {
    screen_id: "notifications",
    name: "Notifications",
    screen_type: "hub",
    allowed_roles: ["student", "parent", "teacher", "admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  // notification-detail is a Fixed screen (not in screenRegistry for Platform Studio)
  "announcements": {
    screen_id: "announcements",
    name: "Announcements",
    screen_type: "hub",
    allowed_roles: ["student", "parent", "teacher", "admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "messages": {
    screen_id: "messages",
    name: "Messages",
    screen_type: "hub",
    allowed_roles: ["student", "parent", "teacher", "admin"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "teacher-contacts": {
    screen_id: "teacher-contacts",
    name: "Teacher Contacts",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "ai-insights": {
    screen_id: "ai-insights",
    name: "AI Insights",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "ai-predictions": {
    screen_id: "ai-predictions",
    name: "AI Predictions",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "ai-recommendations": {
    screen_id: "ai-recommendations",
    name: "AI Recommendations",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "ai-alerts": {
    screen_id: "ai-alerts",
    name: "AI Alerts",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
  "comparison-analytics": {
    screen_id: "comparison-analytics",
    name: "Comparison Analytics",
    screen_type: "hub",
    allowed_roles: ["parent"],
    default_layout: "vertical",
    scrollable: true,
    pull_to_refresh: true,
    header_visible: true,
  },
};

// Helper functions
export function getScreen(screenId: string): ScreenDefinition | undefined {
  return screenRegistry[screenId];
}

export function getScreensForRole(role: string): ScreenDefinition[] {
  return Object.values(screenRegistry).filter((s) =>
    s.allowed_roles.includes(role as any)
  );
}

export function getAllScreens(): ScreenDefinition[] {
  return Object.values(screenRegistry);
}

// Default root screens per role
export const DEFAULT_ROOT_SCREENS: Record<string, string> = {
  student: "student-home",
  teacher: "teacher-home",
  parent: "parent-home",
  admin: "admin-home",
};
