import { WidgetMetadata, WidgetCategory } from "@/types";

// Complete widget registry with all 60+ widgets
export const widgetRegistry: Record<string, WidgetMetadata> = {
  // ============ SCHEDULE WIDGETS ============
  "schedule.today": {
    id: "schedule.today",
    name: "Today's Schedule",
    description: "Shows today's classes and events",
    category: "schedule",
    icon: "calendar",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "schedule.weekly": {
    id: "schedule.weekly",
    name: "Weekly Calendar",
    description: "Weekly calendar view",
    category: "schedule",
    icon: "calendar",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "schedule.upcoming-class": {
    id: "schedule.upcoming-class",
    name: "Upcoming Class",
    description: "Next class countdown",
    category: "schedule",
    icon: "clock",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "schedule.live-now": {
    id: "schedule.live-now",
    name: "Live Now",
    description: "Currently live classes",
    category: "schedule",
    icon: "video",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "live_classes",
  },
  "live.class": {
    id: "live.class",
    name: "Live Class Card",
    description: "Upcoming or current live class with join button and countdown",
    category: "schedule",
    icon: "video",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "schedule.live",
  },

  // ============ STUDY WIDGETS ============
  "library.recent": {
    id: "library.recent",
    name: "Recent Library",
    description: "Recently accessed content",
    category: "study",
    icon: "book",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "library.favorites": {
    id: "library.favorites",
    name: "Favorites",
    description: "Bookmarked content",
    category: "study",
    icon: "star",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "library.subjects": {
    id: "library.subjects",
    name: "Subjects",
    description: "Subject-wise content",
    category: "study",
    icon: "folder",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "library.continue": {
    id: "library.continue",
    name: "Continue Learning (Legacy)",
    description: "Resume where you left off",
    category: "study",
    icon: "play",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "continue.learning": {
    id: "continue.learning",
    name: "Continue Learning",
    description: "Pick up where you left off with recent lessons, videos, and activities",
    category: "study",
    icon: "book-clock",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "content.featured": {
    id: "content.featured",
    name: "Featured Content",
    description: "Highlighted resources",
    category: "study",
    icon: "sparkles",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },

  // ============ ASSESSMENT WIDGETS ============
  "assignments.pending": {
    id: "assignments.pending",
    name: "Pending Assignments",
    description: "Assignments due soon",
    category: "assessment",
    icon: "clipboard",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "assignments.submitted": {
    id: "assignments.submitted",
    name: "Submitted Assignments",
    description: "Recently submitted work",
    category: "assessment",
    icon: "check-circle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "assignments.to-grade": {
    id: "assignments.to-grade",
    name: "To Grade",
    description: "Assignments pending grading",
    category: "assessment",
    icon: "edit",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "tests.upcoming": {
    id: "tests.upcoming",
    name: "Upcoming Tests",
    description: "Scheduled tests",
    category: "assessment",
    icon: "file-text",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "tests.results": {
    id: "tests.results",
    name: "Test Results",
    description: "Recent test scores",
    category: "assessment",
    icon: "bar-chart",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "tests.analytics": {
    id: "tests.analytics",
    name: "Test Analytics",
    description: "Performance analysis",
    category: "assessment",
    icon: "pie-chart",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "analytics.snapshot": {
    id: "analytics.snapshot",
    name: "Analytics Snapshot",
    description: "Weekly overview with study time, assignments, tests, and subject progress",
    category: "analytics",
    icon: "bar-chart-2",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "progress.analytics",
  },

  // ============ DOUBTS WIDGETS ============
  "doubts.inbox": {
    id: "doubts.inbox",
    name: "Doubts Inbox",
    description: "Recent doubts and status",
    category: "doubts",
    icon: "help-circle",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "doubts",
  },
  "doubts.quick-ask": {
    id: "doubts.quick-ask",
    name: "Quick Ask",
    description: "Quick doubt submission",
    category: "doubts",
    icon: "message-circle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
    requiredFeatureId: "doubts",
  },
  "doubts.answered": {
    id: "doubts.answered",
    name: "Answered Doubts",
    description: "Resolved questions",
    category: "doubts",
    icon: "check-circle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "doubts",
  },
  "doubts.to-answer": {
    id: "doubts.to-answer",
    name: "Doubts to Answer",
    description: "Pending student questions",
    category: "doubts",
    icon: "inbox",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "doubts",
  },

  // ============ PROGRESS WIDGETS ============
  "progress.snapshot": {
    id: "progress.snapshot",
    name: "Progress Snapshot",
    description: "Overall progress summary",
    category: "progress",
    icon: "trending-up",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "progress.subject-wise": {
    id: "progress.subject-wise",
    name: "Subject Progress",
    description: "Progress by subject",
    category: "progress",
    icon: "bar-chart-2",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "progress.streak": {
    id: "progress.streak",
    name: "Learning Streak",
    description: "Daily streak counter",
    category: "progress",
    icon: "flame",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "gamification",
  },
  "streak.tracker": {
    id: "streak.tracker",
    name: "Streak Tracker",
    description: "Track study streaks with achievements, weekly goals, and motivation",
    category: "progress",
    icon: "flame",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "progress.analytics",
  },
  "progress.goals": {
    id: "progress.goals",
    name: "Learning Goals",
    description: "Track learning goals with progress bars and deadlines",
    category: "progress",
    icon: "flag-checkered",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "list"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "stats.grid": {
    id: "stats.grid",
    name: "Stats Grid",
    description: "User statistics in grid layout",
    category: "progress",
    icon: "grid",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "quests.active": {
    id: "quests.active",
    name: "Active Quests",
    description: "Daily and weekly quests with progress",
    category: "progress",
    icon: "flag",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "gamification",
  },
  "progress.weak-areas": {
    id: "progress.weak-areas",
    name: "Weak Areas",
    description: "Topics needing attention",
    category: "progress",
    icon: "alert-triangle",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "weak.topics": {
    id: "weak.topics",
    name: "Topics to Strengthen",
    description: "Topics needing attention with mastery percentage and practice recommendations",
    category: "progress",
    icon: "alert-triangle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "detail"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "progress.analytics",
  },

  // ============ SOCIAL WIDGETS ============
  "peers.groups": {
    id: "peers.groups",
    name: "Study Groups",
    description: "Your study groups",
    category: "social",
    icon: "users",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },
  "peers.leaderboard": {
    id: "peers.leaderboard",
    name: "Leaderboard",
    description: "Class rankings",
    category: "social",
    icon: "trophy",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
    requiredFeatureId: "gamification",
  },
  "peers.suggestions": {
    id: "peers.suggestions",
    name: "Peer Suggestions",
    description: "Connect with classmates",
    category: "social",
    icon: "user-plus",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },
  "feed.class": {
    id: "feed.class",
    name: "Class Feed",
    description: "Class activity feed",
    category: "social",
    icon: "activity",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "feed.announcements": {
    id: "feed.announcements",
    name: "Announcements",
    description: "Important announcements",
    category: "social",
    icon: "megaphone",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },

  // ============ AI WIDGETS ============
  "ai.tutor-chat": {
    id: "ai.tutor-chat",
    name: "AI Tutor",
    description: "Chat with AI tutor",
    category: "ai",
    icon: "bot",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai_tutor",
  },
  "ai.recommendations": {
    id: "ai.recommendations",
    name: "AI Recommendations",
    description: "Personalized suggestions",
    category: "ai",
    icon: "sparkles",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "ai_tutor",
  },
  "ai.tools": {
    id: "ai.tools",
    name: "AI Tools",
    description: "AI-powered learning tools like AI Tutor, Practice Generator, Summary Generator",
    category: "ai",
    icon: "robot",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai.tutor",
  },
  "ai.learning-insights": {
    id: "ai.learning-insights",
    name: "Learning Insights",
    description: "AI-generated learning insights showing strengths, weaknesses, recommendations, and trends",
    category: "ai",
    icon: "lightbulb-on",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai.tutor",
  },
  "ai.performance-predictions": {
    id: "ai.performance-predictions",
    name: "Performance Predictions",
    description: "AI-powered performance predictions for exams, grades, milestones, and risk alerts",
    category: "ai",
    icon: "chart-line",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai.tutor",
  },
  "ai.weak-topic-alerts": {
    id: "ai.weak-topic-alerts",
    name: "Weak Topic Alerts",
    description: "AI-generated alerts for weak topics needing attention with severity levels and practice recommendations",
    category: "ai",
    icon: "alert-decagram",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai.tutor",
  },
  "ai.study-recommendations": {
    id: "ai.study-recommendations",
    name: "Study Recommendations",
    description: "AI-powered personalized study recommendations with content, practice, revision, and challenge suggestions",
    category: "ai",
    icon: "lightbulb-on",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai.tutor",
  },
  "notes.summary": {
    id: "notes.summary",
    name: "Notes Summary",
    description: "Student notes overview with total count, pinned notes, recent notes, and word count",
    category: "study",
    icon: "note-multiple",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "study.notes",
  },
  "recent.viewed": {
    id: "recent.viewed",
    name: "Recently Viewed",
    description: "Shows recently viewed content like videos, lessons, notes, and assignments with progress",
    category: "study",
    icon: "history",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "study.history",
  },
  "week.calendar": {
    id: "week.calendar",
    name: "Week Calendar",
    description: "Weekly calendar view showing classes and events grouped by day with navigation",
    category: "schedule",
    icon: "calendar-week",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "schedule.calendar",
  },
  "upcoming.events": {
    id: "upcoming.events",
    name: "Upcoming Events",
    description: "Shows upcoming school events like exams, holidays, sports days, and meetings",
    category: "schedule",
    icon: "calendar-star",
    allowedRoles: ["student", "parent", "teacher"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "schedule.events",
  },
  "notifications.preview": {
    id: "notifications.preview",
    name: "Notifications Preview",
    description: "Recent notifications with unread count, priority indicators, and category badges",
    category: "notifications",
    icon: "bell",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "notifications",
  },
  "tasks.overview": {
    id: "tasks.overview",
    name: "Tasks Overview",
    description: "Combined view of assignments and tests with counts, due dates, and overdue indicators",
    category: "assessment",
    icon: "clipboard-list",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "assessment",
  },
  "downloads.summary": {
    id: "downloads.summary",
    name: "Downloads Summary",
    description: "Shows downloaded content with storage used, file counts, and recent downloads",
    category: "study",
    icon: "download",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "study.downloads",
  },
  "connections.list": {
    id: "connections.list",
    name: "Connections List",
    description: "Shows student connections with online status, mutual subjects, XP, and streaks",
    category: "social",
    icon: "account-group",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "peers.network",
  },
  "suggestions.peers": {
    id: "suggestions.peers",
    name: "Suggested Peers",
    description: "Shows peer suggestions with match score, mutual subjects, and connect actions",
    category: "social",
    icon: "account-search",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "peers.network",
  },
  "ai.summary": {
    id: "ai.summary",
    name: "AI Summary",
    description: "AI-generated summaries",
    category: "ai",
    icon: "file-text",
    allowedRoles: ["student"],
    allowedScreenTypes: ["detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai_tutor",
  },
  "ai.practice": {
    id: "ai.practice",
    name: "AI Practice",
    description: "AI-generated practice questions",
    category: "ai",
    icon: "brain",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
    requiredFeatureId: "ai_tutor",
  },

  // ============ AUTOMATION WIDGETS ============
  "automation.n8n-test": {
    id: "automation.n8n-test",
    name: "n8n Webhook Test",
    description: "Test n8n automation webhooks",
    category: "automation",
    icon: "webhook",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "automation",
  },
  "automation.reminders": {
    id: "automation.reminders",
    name: "Reminders",
    description: "Upcoming reminders and scheduled tasks with time tracking, repeat options, and overdue alerts",
    category: "automation",
    icon: "bell-ring",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "automation",
  },
  "automation.streak-protection": {
    id: "automation.streak-protection",
    name: "Streak Protection",
    description: "Displays streak status, protection shields, weekly progress, and quick actions to maintain learning streak",
    category: "automation",
    icon: "shield-check",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "automation",
  },

  // ============ REWARDS WIDGETS ============
  "rewards.shop-preview": {
    id: "rewards.shop-preview",
    name: "Reward Shop Preview",
    description: "Displays featured reward shop items with coins/XP costs, discounts, and rarity badges",
    category: "rewards",
    icon: "gift",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "rewards",
  },
  "rewards.xp-balance": {
    id: "rewards.xp-balance",
    name: "XP & Coins Balance",
    description: "Displays user's XP total, coins balance, current level, progress to next level, and rank",
    category: "rewards",
    icon: "star-four-points",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "rewards",
  },

  // ============ COMMUNITY WIDGETS ============
  "community.feed": {
    id: "community.feed",
    name: "Community Feed",
    description: "Displays community posts, achievements, questions, announcements, and challenges from peers",
    category: "social",
    icon: "account-group",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },
  "study.groups": {
    id: "study.groups",
    name: "Study Groups",
    description: "Displays study groups the user belongs to or can join, with member counts and meeting schedules",
    category: "social",
    icon: "account-group",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },
  "peer.matches": {
    id: "peer.matches",
    name: "Peer Matches",
    description: "AI-generated peer matching suggestions based on learning patterns, common subjects, and goals",
    category: "social",
    icon: "account-search",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },

  // ============ PROFILE & UTILITY WIDGETS ============
  "profile.card": {
    id: "profile.card",
    name: "Profile Card",
    description: "User profile with avatar, name, class, and stats",
    category: "profile",
    icon: "user",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "profile.quickLinks": {
    id: "profile.quickLinks",
    name: "Quick Links",
    description: "Navigation shortcuts for Settings, Edit Profile, Help, and more",
    category: "profile",
    icon: "link",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },

  "profile.stats": {
    id: "profile.stats",
    name: "Profile Stats",
    description: "User statistics",
    category: "profile",
    icon: "bar-chart",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "profile.achievements": {
    id: "profile.achievements",
    name: "Achievements",
    description: "Badges and rewards earned by the user",
    category: "profile",
    icon: "trophy",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "gamification",
  },
  "profile.activity": {
    id: "profile.activity",
    name: "Recent Activity",
    description: "Timeline of recent learning activities",
    category: "profile",
    icon: "activity",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "notifications.recent": {
    id: "notifications.recent",
    name: "Recent Notifications",
    description: "Latest notifications",
    category: "notifications",
    icon: "bell",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "actions.quick": {
    id: "actions.quick",
    name: "Quick Actions",
    description: "Quick action buttons",
    category: "actions",
    icon: "zap",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
  },
  "hero.greeting": {
    id: "hero.greeting",
    name: "Hero Greeting",
    description: "Welcome card with user info",
    category: "profile",
    icon: "smile",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
  },

  // ============ TEACHER WIDGETS ============
  "analytics.class-performance": {
    id: "analytics.class-performance",
    name: "Class Performance",
    description: "Class-wide analytics",
    category: "analytics",
    icon: "bar-chart-2",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "analytics.attendance": {
    id: "analytics.attendance",
    name: "Attendance",
    description: "Attendance tracking",
    category: "analytics",
    icon: "check-square",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "class.roster": {
    id: "class.roster",
    name: "Class Roster",
    description: "Student list",
    category: "analytics",
    icon: "list",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "class.live-controls": {
    id: "class.live-controls",
    name: "Live Class Controls",
    description: "Controls for live class",
    category: "schedule",
    icon: "video",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["detail"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
    requiredFeatureId: "live_classes",
  },

  // ============ PARENT WIDGETS ============
  "parent.children-overview": {
    id: "parent.children-overview",
    name: "Children Overview",
    description: "Cards for each child with quick stats and today's attendance",
    category: "profile",
    icon: "users",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.children",
  },
  "parent.attendance-summary": {
    id: "parent.attendance-summary",
    name: "Attendance Summary",
    description: "Track children's attendance with today's status, weekly and monthly stats",
    category: "analytics",
    icon: "check-square",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.attendance",
  },
  "parent.fee-alerts": {
    id: "parent.fee-alerts",
    name: "Fee Alerts",
    description: "Pending fees, overdue payments, and payment status for all children",
    category: "analytics",
    icon: "credit-card",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.fees",
  },
  "parent.notifications-preview": {
    id: "parent.notifications-preview",
    name: "Parent Notifications",
    description: "Recent notifications with unread count, category icons, and priority indicators",
    category: "notifications",
    icon: "bell",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.notifications",
  },
  "parent.ai-insights-preview": {
    id: "parent.ai-insights-preview",
    name: "Parent AI Insights",
    description: "AI-powered insights about child performance, attendance, and recommendations",
    category: "ai",
    icon: "brain",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.ai-insights",
  },
  "parent.quick-actions": {
    id: "parent.quick-actions",
    name: "Parent Quick Actions",
    description: "Common parent actions like pay fees, message teacher, view reports, and more",
    category: "actions",
    icon: "zap",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.quick-actions",
  },
  "parent.child-progress": {
    id: "parent.child-progress",
    name: "Child Progress Overview",
    description: "Overall academic progress summary with total completion percentage and study hours",
    category: "progress",
    icon: "trending-up",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.progress",
  },
  "parent.child-stats": {
    id: "parent.child-stats",
    name: "Child Stats",
    description: "Learning statistics grid with XP, streak, badges, study time, tests, and assignments",
    category: "progress",
    icon: "bar-chart-2",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.stats",
  },
  "parent.weak-areas": {
    id: "parent.weak-areas",
    name: "Child Weak Areas",
    description: "Topics needing attention with mastery percentage, difficulty, and practice recommendations",
    category: "progress",
    icon: "alert-triangle",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.progress",
  },
  "parent.performance-chart": {
    id: "parent.performance-chart",
    name: "Performance Chart",
    description: "Subject scores with bar charts and weekly XP progress visualization",
    category: "progress",
    icon: "bar-chart-2",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.progress",
  },
  "parent.assignments-pending": {
    id: "parent.assignments-pending",
    name: "Child Pending Assignments",
    description: "Assignments due soon with overdue alerts, due dates, and subject info",
    category: "assessment",
    icon: "clipboard-list",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.assignments",
  },
  "parent.subject-progress": {
    id: "parent.subject-progress",
    name: "Child Subject Progress",
    description: "Subject-wise academic progress with scores, chapters, and test stats",
    category: "progress",
    icon: "book-education",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.progress",
  },
  "parent.report-card-preview": {
    id: "parent.report-card-preview",
    name: "Child Report Card",
    description: "Academic grades summary with overall grade, subject grades, and pass rate",
    category: "progress",
    icon: "file-text",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.progress",
  },
  "parent.messages-inbox": {
    id: "parent.messages-inbox",
    name: "Parent Messages",
    description: "Inbox for messages from teachers and school with unread count and categories",
    category: "notifications",
    icon: "mail",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.messages",
  },
  "parent.announcements": {
    id: "parent.announcements",
    name: "School Announcements",
    description: "School announcements with pinned items, categories, and priority indicators",
    category: "notifications",
    icon: "megaphone",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.announcements",
  },
  "parent.teacher-contacts": {
    id: "parent.teacher-contacts",
    name: "Teacher Contacts",
    description: "Contact teachers with availability status, call, email, and message options",
    category: "social",
    icon: "users",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.teacher-contacts",
  },
  "parent.fee-summary": {
    id: "parent.fee-summary",
    name: "Fee Summary",
    description: "Complete fee overview with total due, overdue amounts, payment status, and pay buttons",
    category: "analytics",
    icon: "wallet",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.fees",
  },
  "parent.pending-fees": {
    id: "parent.pending-fees",
    name: "Pending Fees",
    description: "Fees due soon with urgency indicators, overdue alerts, and quick pay buttons",
    category: "analytics",
    icon: "clock",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.fees",
  },
  "parent.payment-history": {
    id: "parent.payment-history",
    name: "Payment History",
    description: "Record of completed payments with receipt numbers, payment methods, and totals",
    category: "analytics",
    icon: "history",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.fees",
  },
  "parent.ai-predictions": {
    id: "parent.ai-predictions",
    name: "AI Predictions",
    description: "AI-powered predictions and forecasts for child performance, attendance, and behavior",
    category: "ai",
    icon: "brain",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.ai-predictions",
  },
  "parent.ai-recommendations": {
    id: "parent.ai-recommendations",
    name: "AI Recommendations",
    description: "Personalized AI-powered suggestions for study, practice, resources, and activities",
    category: "ai",
    icon: "lightbulb",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.ai-recommendations",
  },
  "parent.ai-alerts": {
    id: "parent.ai-alerts",
    name: "AI Alerts",
    description: "Early warning system with severity-based alerts for academic, attendance, and behavior issues",
    category: "ai",
    icon: "bell-alert",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.ai-alerts",
  },
  "parent.comparison-analytics": {
    id: "parent.comparison-analytics",
    name: "Comparison Analytics",
    description: "Compare child's performance against class average, grade level, and historical data",
    category: "analytics",
    icon: "chart-bar",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.analytics",
  },
  "child.schedule": {
    id: "child.schedule",
    name: "Child Schedule",
    description: "Child's class schedule",
    category: "schedule",
    icon: "calendar",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "child.attendance": {
    id: "child.attendance",
    name: "Child Attendance",
    description: "Child's attendance record",
    category: "analytics",
    icon: "check-square",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "child.selector": {
    id: "child.selector",
    name: "Child Selector",
    description: "Switch between children",
    category: "profile",
    icon: "users",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact"],
    defaultSize: "compact",
  },

  // ============ ADMIN WIDGETS ============
  "admin.hero-card": {
    id: "admin.hero-card",
    name: "Admin Hero Card",
    description: "Admin greeting with avatar, quick stats (users, revenue, alerts), and action buttons",
    category: "profile",
    icon: "user-cog",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.dashboard",
  },
  "admin.stats-grid": {
    id: "admin.stats-grid",
    name: "Admin Stats Grid",
    description: "4-stat grid showing total users, active users, revenue, and alerts with trends",
    category: "analytics",
    icon: "view-grid",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.dashboard",
  },
  "admin.system-health": {
    id: "admin.system-health",
    name: "System Health",
    description: "System health monitoring with uptime, CPU, memory usage, and active users with progress bars",
    category: "analytics",
    icon: "heart-pulse",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.dashboard",
  },
  "admin.stats": {
    id: "admin.stats",
    name: "Admin Stats",
    description: "Platform statistics",
    category: "analytics",
    icon: "activity",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "admin.users": {
    id: "admin.users",
    name: "User Management",
    description: "User overview",
    category: "analytics",
    icon: "users",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "admin.config": {
    id: "admin.config",
    name: "Config Status",
    description: "Configuration status",
    category: "analytics",
    icon: "settings",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "admin.alerts": {
    id: "admin.alerts",
    name: "System Alerts",
    description: "System notifications",
    category: "notifications",
    icon: "alert-circle",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "admin.quick-actions": {
    id: "admin.quick-actions",
    name: "Quick Actions",
    description: "4 quick action buttons for Add User, Reports, Settings, and Audit Logs",
    category: "actions",
    icon: "lightning-bolt",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.dashboard",
  },
  "admin.recent-activity": {
    id: "admin.recent-activity",
    name: "Recent Activity",
    description: "Activity feed showing recent system activities with avatars and timestamps",
    category: "activity",
    icon: "history",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.dashboard",
  },

  // ============ ADMIN USER MANAGEMENT WIDGETS ============
  "users.overview-stats": {
    id: "users.overview-stats",
    name: "User Statistics",
    description: "User statistics showing total, active, pending, and suspended users with trends",
    category: "analytics",
    icon: "users",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.users",
  },
  "users.list": {
    id: "users.list",
    name: "User List",
    description: "Filterable, sortable user list with search, role filter, and status indicators",
    category: "analytics",
    icon: "list",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
    requiredFeatureId: "admin.users",
  },
  "users.pending-approvals": {
    id: "users.pending-approvals",
    name: "Pending Approvals",
    description: "Users awaiting approval with quick approve/reject actions",
    category: "actions",
    icon: "user-check",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.users",
  },
  "users.role-distribution": {
    id: "users.role-distribution",
    name: "Role Distribution",
    description: "Visual breakdown of users by role with percentages and bar chart",
    category: "analytics",
    icon: "pie-chart",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.users",
  },
  "users.bulk-actions": {
    id: "users.bulk-actions",
    name: "Bulk Actions",
    description: "Quick access to bulk user operations like import, export, and bulk approve",
    category: "actions",
    icon: "layers",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "admin.users",
  },
  "users.recent-registrations": {
    id: "users.recent-registrations",
    name: "Recent Registrations",
    description: "Shows recently registered users with role, status, and registration time",
    category: "analytics",
    icon: "user-plus",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.users",
  },

  // ============ ADMIN FINANCE WIDGETS ============
  "finance.revenue-summary": {
    id: "finance.revenue-summary",
    name: "Revenue Summary",
    description: "Revenue overview with total, growth percentage, breakdown by category, and period selector",
    category: "analytics",
    icon: "dollar-sign",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.finances",
  },
  "finance.expense-summary": {
    id: "finance.expense-summary",
    name: "Expense Summary",
    description: "Expense overview with total, growth percentage, breakdown by category (salary, utilities, materials, other), and period selector",
    category: "analytics",
    icon: "credit-card",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.finances",
  },
  "finance.net-profit": {
    id: "finance.net-profit",
    name: "Net Profit",
    description: "Net profit overview with revenue minus expenses, profit margin percentage, growth trend, and period comparison",
    category: "analytics",
    icon: "trending-up",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.finances",
  },
  "finance.transactions": {
    id: "finance.transactions",
    name: "Recent Transactions",
    description: "List of recent financial transactions with type indicators (income/expense), status chips, category, and amount formatting",
    category: "analytics",
    icon: "list",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.finances",
  },
  "finance.pending-payments": {
    id: "finance.pending-payments",
    name: "Pending Payments",
    description: "Outstanding payments list with overdue indicators, due dates, total pending amount, and payment status tracking",
    category: "analytics",
    icon: "clock",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.finances",
  },
  "finance.monthly-chart": {
    id: "finance.monthly-chart",
    name: "Monthly Trend Chart",
    description: "Line chart showing revenue vs expenses trend over 3, 6, or 12 months with summary statistics",
    category: "analytics",
    icon: "chart-line",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "expanded",
    requiredFeatureId: "admin.finances",
  },
  "finance.category-breakdown": {
    id: "finance.category-breakdown",
    name: "Category Breakdown",
    description: "Pie chart showing revenue and expense breakdown by category with percentages, legend, and period/type selectors",
    category: "analytics",
    icon: "chart-pie",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.finances",
  },
  "finance.collection-rate": {
    id: "finance.collection-rate",
    name: "Collection Rate",
    description: "Fee collection efficiency widget showing collection rate percentage, progress bar, collected vs pending amounts, and status thresholds",
    category: "analytics",
    icon: "percent",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.finances",
  },
  "admin.student-fees-dashboard": {
    id: "admin.student-fees-dashboard",
    name: "Student Fees Dashboard",
    description: "Coaching-specific fee collection dashboard showing total collected, pending, overdue amounts with student counts, collection rate progress bar, today's collection, and send reminder action",
    category: "fees",
    icon: "cash-multiple",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.fees",
  },
  "admin.fee-collection-trend": {
    id: "admin.fee-collection-trend",
    name: "Fee Collection Trend",
    description: "Monthly fee collection bar chart showing expected vs actual amounts, period selector (6/12 months), month-over-month growth indicator, and year-to-date progress",
    category: "fees",
    icon: "chart-line",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.fees",
  },
  "admin.teacher-payroll": {
    id: "admin.teacher-payroll",
    name: "Teacher Payroll",
    description: "Teacher payroll summary showing total payroll amount, paid vs pending breakdown with counts, progress bar, next payment due date, overdue alerts, and process salaries button",
    category: "payroll",
    icon: "wallet",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.payroll",
  },
  "admin.batch-performance": {
    id: "admin.batch-performance",
    name: "Batch Performance",
    description: "Top batches by average score with pass percentage, student count, comparison with previous term, color-coded performance indicators, and rank badges",
    category: "academic",
    icon: "school",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.academic",
  },
  "admin.attendance-overview": {
    id: "admin.attendance-overview",
    name: "Attendance Overview",
    description: "Today's student and teacher attendance with percentage, absent list, weekly trend sparkline, and low attendance alerts",
    category: "academic",
    icon: "clipboard-check",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.academic",
  },
  "admin.admission-stats": {
    id: "admin.admission-stats",
    name: "Admission Stats",
    description: "New admissions with inquiries, conversions, program breakdown, pending follow-ups, and add inquiry button",
    category: "academic",
    icon: "school",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.academic",
  },
  "analytics.kpi-grid": {
    id: "analytics.kpi-grid",
    name: "KPI Grid",
    description: "Configurable grid of key performance indicators showing metrics with trends, growth percentages, and visual indicators",
    category: "analytics",
    icon: "layout-grid",
    allowedRoles: ["admin", "teacher", "parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "analytics",
  },
  "analytics.trends": {
    id: "analytics.trends",
    name: "Trends",
    description: "Line chart showing trends over time for users, revenue, engagement, or content with metric/period selectors, change indicator, and statistics",
    category: "analytics",
    icon: "trending-up",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.analytics",
  },
  "analytics.engagement": {
    id: "analytics.engagement",
    name: "Engagement",
    description: "User engagement metrics including DAU, WAU, engagement rate, retention rate, activity trends, role breakdown, and top engaged users",
    category: "analytics",
    icon: "activity",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.analytics",
  },
  "analytics.growth": {
    id: "analytics.growth",
    name: "Growth Metrics",
    description: "Growth metrics dashboard showing new users, revenue, engagement rate, and content views with period selectors, target progress, trend charts, and highlights",
    category: "analytics",
    icon: "chart-line",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.analytics",
  },
  "analytics.comparisons": {
    id: "analytics.comparisons",
    name: "Period Comparisons",
    description: "Compare key metrics across time periods with current vs previous values, change indicators, and trend summary",
    category: "analytics",
    icon: "compare-horizontal",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.analytics",
  },
  "content.stats": {
    id: "content.stats",
    name: "Content Statistics",
    description: "Overview of content library with total content, views, ratings, breakdown by type and status",
    category: "content",
    icon: "file-document-multiple",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.content",
  },
  "content.list": {
    id: "content.list",
    name: "Content Library",
    description: "Filterable, sortable list of content items with search, type filter, and status filter",
    category: "content",
    icon: "file-document-outline",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub", "list"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "expanded",
    requiredFeatureId: "admin.content",
  },
  "content.categories": {
    id: "content.categories",
    name: "Content Categories",
    description: "Display content categories with counts, views, and ratings in grid or list layout",
    category: "content",
    icon: "folder-multiple",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.content",
  },
  "org.tree": {
    id: "org.tree",
    name: "Organization Tree",
    description: "Display hierarchical organization structure with organizations, departments, classes, and batches",
    category: "content",
    icon: "sitemap",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub", "detail"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.organization",
  },
  "org.class-list": {
    id: "org.class-list",
    name: "Class List",
    description: "Display list of classes with search, filters, member counts, and department info",
    category: "content",
    icon: "google-classroom",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub", "list"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.organization",
  },
  "org.quick-create": {
    id: "org.quick-create",
    name: "Quick Create",
    description: "Quick action buttons to create organization entities like organizations, departments, classes, and batches",
    category: "actions",
    icon: "plus-circle",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.organization",
  },

  // ============ ADMIN PROFILE WIDGETS ============
  "profile.activity": {
    id: "profile.activity",
    name: "Admin Activity Log",
    description: "Timeline of admin activities with today's stats, grouped by date, and activity type filtering",
    category: "profile",
    icon: "history",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.profile",
  },

  // ============ MEDIA WIDGETS ============
  "media.banner": {
    id: "media.banner",
    name: "Media Banner",
    description: "Versatile media widget for images, videos, YouTube, or carousels with overlay text and CTA buttons",
    category: "media",
    icon: "image",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub", "detail", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "media.banner-1": {
    id: "media.banner-1",
    name: "Media Banner Slot 1",
    description: "First media banner slot - use for primary promotional content",
    category: "media",
    icon: "image",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub", "detail", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "media.banner-2": {
    id: "media.banner-2",
    name: "Media Banner Slot 2",
    description: "Second media banner slot - use for secondary content",
    category: "media",
    icon: "image",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub", "detail", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "media.banner-3": {
    id: "media.banner-3",
    name: "Media Banner Slot 3",
    description: "Third media banner slot - use for additional content",
    category: "media",
    icon: "image",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub", "detail", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "media.hero": {
    id: "media.hero",
    name: "Hero Banner",
    description: "Full-width hero banner for top of screens - ideal for welcome messages and featured content",
    category: "media",
    icon: "panorama-wide-angle",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "media.promo": {
    id: "media.promo",
    name: "Promo Carousel",
    description: "Promotional carousel for announcements, offers, and featured items",
    category: "media",
    icon: "view-carousel",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "media.ad": {
    id: "media.ad",
    name: "Ad Banner",
    description: "Compact ad/sponsor banner for monetization or partner content",
    category: "media",
    icon: "advertisements",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub", "detail", "any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
};

// Helper functions
export function getWidget(widgetId: string): WidgetMetadata | undefined {
  return widgetRegistry[widgetId];
}

export function getWidgetsByCategory(category: WidgetCategory): WidgetMetadata[] {
  return Object.values(widgetRegistry).filter((w) => w.category === category);
}

export function getWidgetsForRole(role: string): WidgetMetadata[] {
  return Object.values(widgetRegistry).filter((w) =>
    w.allowedRoles.includes(role as any)
  );
}

export function getAllWidgets(): WidgetMetadata[] {
  return Object.values(widgetRegistry);
}

export const WIDGET_CATEGORIES: { id: WidgetCategory; label: string; icon: string }[] = [
  { id: "schedule", label: "Schedule", icon: "calendar" },
  { id: "study", label: "Study", icon: "book" },
  { id: "assessment", label: "Assessment", icon: "clipboard" },
  { id: "doubts", label: "Doubts", icon: "help-circle" },
  { id: "progress", label: "Progress", icon: "trending-up" },
  { id: "social", label: "Social", icon: "users" },
  { id: "ai", label: "AI", icon: "bot" },
  { id: "automation", label: "Automation", icon: "webhook" },
  { id: "media", label: "Media", icon: "image" },
  { id: "profile", label: "Profile", icon: "user" },
  { id: "notifications", label: "Notifications", icon: "bell" },
  { id: "actions", label: "Actions", icon: "zap" },
  { id: "content", label: "Content", icon: "file-text" },
  { id: "analytics", label: "Analytics", icon: "bar-chart" },
  { id: "fees", label: "Fees", icon: "indian-rupee" },
  { id: "payroll", label: "Payroll", icon: "wallet" },
  { id: "academic", label: "Academic", icon: "school" },
];
