import { WidgetMetadata, WidgetCategory } from "@/types";

// Complete widget registry with all 60+ widgets
export const widgetRegistry: Record<string, WidgetMetadata> = {
  // ============ SCHEDULE WIDGETS ============
  "schedule.today": {
    id: "schedule.today",
    name: "Today's Schedule",
    description: "Shows today's classes and events",
    category: "schedule",
    icon: "calendar",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "schedule.weekly": {
    id: "schedule.weekly",
    name: "Weekly Calendar",
    description: "Weekly calendar view",
    category: "schedule",
    icon: "calendar",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "schedule.upcoming-class": {
    id: "schedule.upcoming-class",
    name: "Upcoming Class",
    description: "Next class countdown",
    category: "schedule",
    icon: "clock",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "schedule.live-now": {
    id: "schedule.live-now",
    name: "Live Now",
    description: "Currently live classes",
    category: "schedule",
    icon: "video",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "live_classes",
  },

  // ============ STUDY WIDGETS ============
  "library.recent": {
    id: "library.recent",
    name: "Recent Library",
    description: "Recently accessed content",
    category: "study",
    icon: "book",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "library.favorites": {
    id: "library.favorites",
    name: "Favorites",
    description: "Bookmarked content",
    category: "study",
    icon: "star",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "library.subjects": {
    id: "library.subjects",
    name: "Subjects",
    description: "Subject-wise content",
    category: "study",
    icon: "folder",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "library.continue": {
    id: "library.continue",
    name: "Continue Learning (Legacy)",
    description: "Resume where you left off",
    category: "study",
    icon: "play",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "continue.learning": {
    id: "continue.learning",
    name: "Continue Learning",
    description: "Pick up where you left off with recent lessons, videos, and activities",
    category: "study",
    icon: "book-clock",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "content.featured": {
    id: "content.featured",
    name: "Featured Content",
    description: "Highlighted resources",
    category: "study",
    icon: "sparkles",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },

  // ============ ASSESSMENT WIDGETS ============
  "assignments.pending": {
    id: "assignments.pending",
    name: "Pending Assignments",
    description: "Assignments due soon",
    category: "assessment",
    icon: "clipboard",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "assignments.submitted": {
    id: "assignments.submitted",
    name: "Submitted Assignments",
    description: "Recently submitted work",
    category: "assessment",
    icon: "check-circle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "assignments.to-grade": {
    id: "assignments.to-grade",
    name: "To Grade",
    description: "Assignments pending grading",
    category: "assessment",
    icon: "edit",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "tests.upcoming": {
    id: "tests.upcoming",
    name: "Upcoming Tests",
    description: "Scheduled tests",
    category: "assessment",
    icon: "file-text",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "tests.results": {
    id: "tests.results",
    name: "Test Results",
    description: "Recent test scores",
    category: "assessment",
    icon: "bar-chart",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "tests.analytics": {
    id: "tests.analytics",
    name: "Test Analytics",
    description: "Performance analysis",
    category: "assessment",
    icon: "pie-chart",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "analytics.snapshot": {
    id: "analytics.snapshot",
    name: "Analytics Snapshot",
    description: "Weekly overview with study time, assignments, tests, and subject progress",
    category: "analytics",
    icon: "bar-chart-2",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "progress.analytics",
  },

  // ============ DOUBTS WIDGETS ============
  "doubts.inbox": {
    id: "doubts.inbox",
    name: "Doubts Inbox",
    description: "Recent doubts and status",
    category: "doubts",
    icon: "help-circle",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "doubts",
  },
  "doubts.quick-ask": {
    id: "doubts.quick-ask",
    name: "Quick Ask",
    description: "Quick doubt submission",
    category: "doubts",
    icon: "message-circle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
    requiredFeatureId: "doubts",
  },
  "doubts.answered": {
    id: "doubts.answered",
    name: "Answered Doubts",
    description: "Resolved questions",
    category: "doubts",
    icon: "check-circle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "doubts",
  },
  "doubts.to-answer": {
    id: "doubts.to-answer",
    name: "Doubts to Answer",
    description: "Pending student questions",
    category: "doubts",
    icon: "inbox",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "doubts",
  },

  // ============ PROGRESS WIDGETS ============
  "progress.snapshot": {
    id: "progress.snapshot",
    name: "Progress Snapshot",
    description: "Overall progress summary",
    category: "progress",
    icon: "trending-up",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "progress.subject-wise": {
    id: "progress.subject-wise",
    name: "Subject Progress",
    description: "Progress by subject",
    category: "progress",
    icon: "bar-chart-2",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "progress.streak": {
    id: "progress.streak",
    name: "Learning Streak",
    description: "Daily streak counter",
    category: "progress",
    icon: "flame",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "gamification",
  },
  "progress.goals": {
    id: "progress.goals",
    name: "Learning Goals",
    description: "Track learning goals with progress bars and deadlines",
    category: "progress",
    icon: "flag-checkered",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "list"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "stats.grid": {
    id: "stats.grid",
    name: "Stats Grid",
    description: "User statistics in grid layout",
    category: "progress",
    icon: "grid",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "quests.active": {
    id: "quests.active",
    name: "Active Quests",
    description: "Daily and weekly quests with progress",
    category: "progress",
    icon: "flag",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "gamification",
  },
  "progress.weak-areas": {
    id: "progress.weak-areas",
    name: "Weak Areas",
    description: "Topics needing attention",
    category: "progress",
    icon: "alert-triangle",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },

  // ============ SOCIAL WIDGETS ============
  "peers.groups": {
    id: "peers.groups",
    name: "Study Groups",
    description: "Your study groups",
    category: "social",
    icon: "users",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },
  "peers.leaderboard": {
    id: "peers.leaderboard",
    name: "Leaderboard",
    description: "Class rankings",
    category: "social",
    icon: "trophy",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
    requiredFeatureId: "gamification",
  },
  "peers.suggestions": {
    id: "peers.suggestions",
    name: "Peer Suggestions",
    description: "Connect with classmates",
    category: "social",
    icon: "user-plus",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },
  "feed.class": {
    id: "feed.class",
    name: "Class Feed",
    description: "Class activity feed",
    category: "social",
    icon: "activity",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "feed.announcements": {
    id: "feed.announcements",
    name: "Announcements",
    description: "Important announcements",
    category: "social",
    icon: "megaphone",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },

  // ============ AI WIDGETS ============
  "ai.tutor-chat": {
    id: "ai.tutor-chat",
    name: "AI Tutor",
    description: "Chat with AI tutor",
    category: "ai",
    icon: "bot",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai_tutor",
  },
  "ai.recommendations": {
    id: "ai.recommendations",
    name: "AI Recommendations",
    description: "Personalized suggestions",
    category: "ai",
    icon: "sparkles",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "ai_tutor",
  },
  "ai.summary": {
    id: "ai.summary",
    name: "AI Summary",
    description: "AI-generated summaries",
    category: "ai",
    icon: "file-text",
    allowedRoles: ["student"],
    allowedScreenTypes: ["detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai_tutor",
  },
  "ai.practice": {
    id: "ai.practice",
    name: "AI Practice",
    description: "AI-generated practice questions",
    category: "ai",
    icon: "brain",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
    requiredFeatureId: "ai_tutor",
  },

  // ============ PROFILE & UTILITY WIDGETS ============
  "profile.card": {
    id: "profile.card",
    name: "Profile Card",
    description: "User profile with avatar, name, class, and stats",
    category: "profile",
    icon: "user",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "profile.quickLinks": {
    id: "profile.quickLinks",
    name: "Quick Links",
    description: "Navigation shortcuts for Settings, Edit Profile, Help, and more",
    category: "profile",
    icon: "link",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },

  "profile.stats": {
    id: "profile.stats",
    name: "Profile Stats",
    description: "User statistics",
    category: "profile",
    icon: "bar-chart",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "profile.achievements": {
    id: "profile.achievements",
    name: "Achievements",
    description: "Badges and rewards earned by the user",
    category: "profile",
    icon: "trophy",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "gamification",
  },
  "profile.activity": {
    id: "profile.activity",
    name: "Recent Activity",
    description: "Timeline of recent learning activities",
    category: "profile",
    icon: "activity",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "notifications.recent": {
    id: "notifications.recent",
    name: "Recent Notifications",
    description: "Latest notifications",
    category: "notifications",
    icon: "bell",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "actions.quick": {
    id: "actions.quick",
    name: "Quick Actions",
    description: "Quick action buttons",
    category: "actions",
    icon: "zap",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
  },
  "hero.greeting": {
    id: "hero.greeting",
    name: "Hero Greeting",
    description: "Welcome card with user info",
    category: "profile",
    icon: "smile",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
  },

  // ============ TEACHER WIDGETS ============
  "analytics.class-performance": {
    id: "analytics.class-performance",
    name: "Class Performance",
    description: "Class-wide analytics",
    category: "analytics",
    icon: "bar-chart-2",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "analytics.attendance": {
    id: "analytics.attendance",
    name: "Attendance",
    description: "Attendance tracking",
    category: "analytics",
    icon: "check-square",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "class.roster": {
    id: "class.roster",
    name: "Class Roster",
    description: "Student list",
    category: "analytics",
    icon: "list",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "class.live-controls": {
    id: "class.live-controls",
    name: "Live Class Controls",
    description: "Controls for live class",
    category: "schedule",
    icon: "video",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["detail"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
    requiredFeatureId: "live_classes",
  },

  // ============ PARENT WIDGETS ============
  "child.progress": {
    id: "child.progress",
    name: "Child Progress",
    description: "Child's learning progress",
    category: "progress",
    icon: "trending-up",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "child.schedule": {
    id: "child.schedule",
    name: "Child Schedule",
    description: "Child's class schedule",
    category: "schedule",
    icon: "calendar",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "child.attendance": {
    id: "child.attendance",
    name: "Child Attendance",
    description: "Child's attendance record",
    category: "analytics",
    icon: "check-square",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "child.selector": {
    id: "child.selector",
    name: "Child Selector",
    description: "Switch between children",
    category: "profile",
    icon: "users",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact"],
    defaultSize: "compact",
  },

  // ============ ADMIN WIDGETS ============
  "admin.stats": {
    id: "admin.stats",
    name: "Admin Stats",
    description: "Platform statistics",
    category: "analytics",
    icon: "activity",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "admin.users": {
    id: "admin.users",
    name: "User Management",
    description: "User overview",
    category: "analytics",
    icon: "users",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "admin.config": {
    id: "admin.config",
    name: "Config Status",
    description: "Configuration status",
    category: "analytics",
    icon: "settings",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "admin.alerts": {
    id: "admin.alerts",
    name: "System Alerts",
    description: "System notifications",
    category: "notifications",
    icon: "alert-circle",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
};

// Helper functions
export function getWidget(widgetId: string): WidgetMetadata | undefined {
  return widgetRegistry[widgetId];
}

export function getWidgetsByCategory(category: WidgetCategory): WidgetMetadata[] {
  return Object.values(widgetRegistry).filter((w) => w.category === category);
}

export function getWidgetsForRole(role: string): WidgetMetadata[] {
  return Object.values(widgetRegistry).filter((w) =>
    w.allowedRoles.includes(role as any)
  );
}

export function getAllWidgets(): WidgetMetadata[] {
  return Object.values(widgetRegistry);
}

export const WIDGET_CATEGORIES: { id: WidgetCategory; label: string; icon: string }[] = [
  { id: "schedule", label: "Schedule", icon: "calendar" },
  { id: "study", label: "Study", icon: "book" },
  { id: "assessment", label: "Assessment", icon: "clipboard" },
  { id: "doubts", label: "Doubts", icon: "help-circle" },
  { id: "progress", label: "Progress", icon: "trending-up" },
  { id: "social", label: "Social", icon: "users" },
  { id: "ai", label: "AI", icon: "bot" },
  { id: "profile", label: "Profile", icon: "user" },
  { id: "notifications", label: "Notifications", icon: "bell" },
  { id: "actions", label: "Actions", icon: "zap" },
  { id: "analytics", label: "Analytics", icon: "bar-chart" },
];
