import { WidgetMetadata, WidgetCategory } from "@/types";

// Complete widget registry with all 60+ widgets
export const widgetRegistry: Record<string, WidgetMetadata> = {
  // ============ SCHEDULE WIDGETS ============
  "schedule.today": {
    id: "schedule.today",
    name: "Today's Schedule",
    description: "Shows today's classes and events",
    category: "schedule",
    icon: "calendar",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "schedule.weekly": {
    id: "schedule.weekly",
    name: "Weekly Calendar",
    description: "Weekly calendar view",
    category: "schedule",
    icon: "calendar",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "schedule.upcoming-class": {
    id: "schedule.upcoming-class",
    name: "Upcoming Class",
    description: "Next class countdown",
    category: "schedule",
    icon: "clock",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "schedule.live-now": {
    id: "schedule.live-now",
    name: "Live Now",
    description: "Currently live classes",
    category: "schedule",
    icon: "video",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "live_classes",
  },
  "live.class": {
    id: "live.class",
    name: "Live Class Card",
    description: "Upcoming or current live class with join button and countdown",
    category: "schedule",
    icon: "video",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "schedule.live",
  },

  // ============ STUDY WIDGETS ============
  "library.recent": {
    id: "library.recent",
    name: "Recent Library",
    description: "Recently accessed content",
    category: "study",
    icon: "book",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "library.favorites": {
    id: "library.favorites",
    name: "Favorites",
    description: "Bookmarked content",
    category: "study",
    icon: "star",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "library.subjects": {
    id: "library.subjects",
    name: "Subjects",
    description: "Subject-wise content",
    category: "study",
    icon: "folder",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "library.continue": {
    id: "library.continue",
    name: "Continue Learning (Legacy)",
    description: "Resume where you left off",
    category: "study",
    icon: "play",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "continue.learning": {
    id: "continue.learning",
    name: "Continue Learning",
    description: "Pick up where you left off with recent lessons, videos, and activities",
    category: "study",
    icon: "book-clock",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "content.featured": {
    id: "content.featured",
    name: "Featured Content",
    description: "Highlighted resources",
    category: "study",
    icon: "sparkles",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },

  // ============ ASSESSMENT WIDGETS ============
  "assignments.pending": {
    id: "assignments.pending",
    name: "Pending Assignments",
    description: "Assignments due soon",
    category: "assessment",
    icon: "clipboard",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "assignments.submitted": {
    id: "assignments.submitted",
    name: "Submitted Assignments",
    description: "Recently submitted work",
    category: "assessment",
    icon: "check-circle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "assignments.to-grade": {
    id: "assignments.to-grade",
    name: "To Grade",
    description: "Assignments pending grading",
    category: "assessment",
    icon: "edit",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "tests.upcoming": {
    id: "tests.upcoming",
    name: "Upcoming Tests",
    description: "Scheduled tests",
    category: "assessment",
    icon: "file-text",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "tests.results": {
    id: "tests.results",
    name: "Test Results",
    description: "Recent test scores",
    category: "assessment",
    icon: "bar-chart",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "tests.analytics": {
    id: "tests.analytics",
    name: "Test Analytics",
    description: "Performance analysis",
    category: "assessment",
    icon: "pie-chart",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "analytics.snapshot": {
    id: "analytics.snapshot",
    name: "Analytics Snapshot",
    description: "Weekly overview with study time, assignments, tests, and subject progress",
    category: "analytics",
    icon: "bar-chart-2",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "progress.analytics",
  },

  // ============ DOUBTS WIDGETS ============
  "doubts.inbox": {
    id: "doubts.inbox",
    name: "Doubts Inbox",
    description: "Recent doubts and status",
    category: "doubts",
    icon: "help-circle",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "doubts",
  },
  "doubts.quick-ask": {
    id: "doubts.quick-ask",
    name: "Quick Ask",
    description: "Quick doubt submission",
    category: "doubts",
    icon: "message-circle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
    requiredFeatureId: "doubts",
  },
  "doubts.answered": {
    id: "doubts.answered",
    name: "Answered Doubts",
    description: "Resolved questions",
    category: "doubts",
    icon: "check-circle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "doubts",
  },
  "doubts.to-answer": {
    id: "doubts.to-answer",
    name: "Doubts to Answer",
    description: "Pending student questions",
    category: "doubts",
    icon: "inbox",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "doubts",
  },

  // ============ PROGRESS WIDGETS ============
  "progress.snapshot": {
    id: "progress.snapshot",
    name: "Progress Snapshot",
    description: "Overall progress summary",
    category: "progress",
    icon: "trending-up",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "progress.subject-wise": {
    id: "progress.subject-wise",
    name: "Subject Progress",
    description: "Progress by subject",
    category: "progress",
    icon: "bar-chart-2",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "progress.streak": {
    id: "progress.streak",
    name: "Learning Streak",
    description: "Daily streak counter",
    category: "progress",
    icon: "flame",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "gamification",
  },
  "streak.tracker": {
    id: "streak.tracker",
    name: "Streak Tracker",
    description: "Track study streaks with achievements, weekly goals, and motivation",
    category: "progress",
    icon: "flame",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "progress.analytics",
  },
  "progress.goals": {
    id: "progress.goals",
    name: "Learning Goals",
    description: "Track learning goals with progress bars and deadlines",
    category: "progress",
    icon: "flag-checkered",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "list"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "stats.grid": {
    id: "stats.grid",
    name: "Stats Grid",
    description: "User statistics in grid layout",
    category: "progress",
    icon: "grid",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "quests.active": {
    id: "quests.active",
    name: "Active Quests",
    description: "Daily and weekly quests with progress",
    category: "progress",
    icon: "flag",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "gamification",
  },
  "progress.weak-areas": {
    id: "progress.weak-areas",
    name: "Weak Areas",
    description: "Topics needing attention",
    category: "progress",
    icon: "alert-triangle",
    allowedRoles: ["student", "parent"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "weak.topics": {
    id: "weak.topics",
    name: "Topics to Strengthen",
    description: "Topics needing attention with mastery percentage and practice recommendations",
    category: "progress",
    icon: "alert-triangle",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "detail"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "progress.analytics",
  },

  // ============ SOCIAL WIDGETS ============
  "peers.groups": {
    id: "peers.groups",
    name: "Study Groups",
    description: "Your study groups",
    category: "social",
    icon: "users",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },
  "peers.leaderboard": {
    id: "peers.leaderboard",
    name: "Leaderboard",
    description: "Class rankings",
    category: "social",
    icon: "trophy",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
    requiredFeatureId: "gamification",
  },
  "peers.suggestions": {
    id: "peers.suggestions",
    name: "Peer Suggestions",
    description: "Connect with classmates",
    category: "social",
    icon: "user-plus",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },
  "feed.class": {
    id: "feed.class",
    name: "Class Feed",
    description: "Class activity feed",
    category: "social",
    icon: "activity",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "feed.announcements": {
    id: "feed.announcements",
    name: "Announcements",
    description: "Important announcements",
    category: "social",
    icon: "megaphone",
    allowedRoles: ["student", "teacher", "parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },

  // ============ AI WIDGETS ============
  "ai.tutor-chat": {
    id: "ai.tutor-chat",
    name: "AI Tutor",
    description: "Chat with AI tutor",
    category: "ai",
    icon: "bot",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai_tutor",
  },
  "ai.recommendations": {
    id: "ai.recommendations",
    name: "AI Recommendations",
    description: "Personalized suggestions",
    category: "ai",
    icon: "sparkles",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
    requiredFeatureId: "ai_tutor",
  },
  "ai.tools": {
    id: "ai.tools",
    name: "AI Tools",
    description: "AI-powered learning tools like AI Tutor, Practice Generator, Summary Generator",
    category: "ai",
    icon: "robot",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai.tutor",
  },
  "ai.learning-insights": {
    id: "ai.learning-insights",
    name: "Learning Insights",
    description: "AI-generated learning insights showing strengths, weaknesses, recommendations, and trends",
    category: "ai",
    icon: "lightbulb-on",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai.tutor",
  },
  "ai.performance-predictions": {
    id: "ai.performance-predictions",
    name: "Performance Predictions",
    description: "AI-powered performance predictions for exams, grades, milestones, and risk alerts",
    category: "ai",
    icon: "chart-line",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai.tutor",
  },
  "ai.weak-topic-alerts": {
    id: "ai.weak-topic-alerts",
    name: "Weak Topic Alerts",
    description: "AI-generated alerts for weak topics needing attention with severity levels and practice recommendations",
    category: "ai",
    icon: "alert-decagram",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai.tutor",
  },
  "ai.study-recommendations": {
    id: "ai.study-recommendations",
    name: "Study Recommendations",
    description: "AI-powered personalized study recommendations with content, practice, revision, and challenge suggestions",
    category: "ai",
    icon: "lightbulb-on",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai.tutor",
  },
  "notes.summary": {
    id: "notes.summary",
    name: "Notes Summary",
    description: "Student notes overview with total count, pinned notes, recent notes, and word count",
    category: "study",
    icon: "note-multiple",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "study.notes",
  },
  "recent.viewed": {
    id: "recent.viewed",
    name: "Recently Viewed",
    description: "Shows recently viewed content like videos, lessons, notes, and assignments with progress",
    category: "study",
    icon: "history",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "study.history",
  },
  "week.calendar": {
    id: "week.calendar",
    name: "Week Calendar",
    description: "Weekly calendar view showing classes and events grouped by day with navigation",
    category: "schedule",
    icon: "calendar-week",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "schedule.calendar",
  },
  "upcoming.events": {
    id: "upcoming.events",
    name: "Upcoming Events",
    description: "Shows upcoming school events like exams, holidays, sports days, and meetings",
    category: "schedule",
    icon: "calendar-star",
    allowedRoles: ["student", "parent", "teacher"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "schedule.events",
  },
  "notifications.preview": {
    id: "notifications.preview",
    name: "Notifications Preview",
    description: "Recent notifications with unread count, priority indicators, and category badges",
    category: "notifications",
    icon: "bell",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "notifications",
  },
  "tasks.overview": {
    id: "tasks.overview",
    name: "Tasks Overview",
    description: "Combined view of assignments and tests with counts, due dates, and overdue indicators",
    category: "assessment",
    icon: "clipboard-list",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "assessment",
  },
  "downloads.summary": {
    id: "downloads.summary",
    name: "Downloads Summary",
    description: "Shows downloaded content with storage used, file counts, and recent downloads",
    category: "study",
    icon: "download",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "study.downloads",
  },
  "connections.list": {
    id: "connections.list",
    name: "Connections List",
    description: "Shows student connections with online status, mutual subjects, XP, and streaks",
    category: "social",
    icon: "account-group",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "peers.network",
  },
  "suggestions.peers": {
    id: "suggestions.peers",
    name: "Suggested Peers",
    description: "Shows peer suggestions with match score, mutual subjects, and connect actions",
    category: "social",
    icon: "account-search",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "peers.network",
  },
  "ai.summary": {
    id: "ai.summary",
    name: "AI Summary",
    description: "AI-generated summaries",
    category: "ai",
    icon: "file-text",
    allowedRoles: ["student"],
    allowedScreenTypes: ["detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "ai_tutor",
  },
  "ai.practice": {
    id: "ai.practice",
    name: "AI Practice",
    description: "AI-generated practice questions",
    category: "ai",
    icon: "brain",
    allowedRoles: ["student"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
    requiredFeatureId: "ai_tutor",
  },

  // ============ AUTOMATION WIDGETS ============
  "automation.n8n-test": {
    id: "automation.n8n-test",
    name: "n8n Webhook Test",
    description: "Test n8n automation webhooks",
    category: "automation",
    icon: "webhook",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "automation",
  },
  "automation.reminders": {
    id: "automation.reminders",
    name: "Reminders",
    description: "Upcoming reminders and scheduled tasks with time tracking, repeat options, and overdue alerts",
    category: "automation",
    icon: "bell-ring",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "automation",
  },
  "automation.streak-protection": {
    id: "automation.streak-protection",
    name: "Streak Protection",
    description: "Displays streak status, protection shields, weekly progress, and quick actions to maintain learning streak",
    category: "automation",
    icon: "shield-check",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "automation",
  },

  // ============ REWARDS WIDGETS ============
  "rewards.shop-preview": {
    id: "rewards.shop-preview",
    name: "Reward Shop Preview",
    description: "Displays featured reward shop items with coins/XP costs, discounts, and rarity badges",
    category: "rewards",
    icon: "gift",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "rewards",
  },
  "rewards.xp-balance": {
    id: "rewards.xp-balance",
    name: "XP & Coins Balance",
    description: "Displays user's XP total, coins balance, current level, progress to next level, and rank",
    category: "rewards",
    icon: "star-four-points",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "rewards",
  },

  // ============ COMMUNITY WIDGETS ============
  "community.feed": {
    id: "community.feed",
    name: "Community Feed",
    description: "Displays community posts, achievements, questions, announcements, and challenges from peers",
    category: "social",
    icon: "account-group",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },
  "study.groups": {
    id: "study.groups",
    name: "Study Groups",
    description: "Displays study groups the user belongs to or can join, with member counts and meeting schedules",
    category: "social",
    icon: "account-group",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },
  "peer.matches": {
    id: "peer.matches",
    name: "Peer Matches",
    description: "AI-generated peer matching suggestions based on learning patterns, common subjects, and goals",
    category: "social",
    icon: "account-search",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub", "any"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "social",
  },

  // ============ PROFILE & UTILITY WIDGETS ============
  "profile.card": {
    id: "profile.card",
    name: "Profile Card",
    description: "User profile with avatar, name, class, and stats",
    category: "profile",
    icon: "user",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "profile.quickLinks": {
    id: "profile.quickLinks",
    name: "Quick Links",
    description: "Navigation shortcuts for Settings, Edit Profile, Help, and more",
    category: "profile",
    icon: "link",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },

  "profile.stats": {
    id: "profile.stats",
    name: "Profile Stats",
    description: "User statistics",
    category: "profile",
    icon: "bar-chart",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["hub", "detail"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "profile.achievements": {
    id: "profile.achievements",
    name: "Achievements",
    description: "Badges and rewards earned by the user",
    category: "profile",
    icon: "trophy",
    allowedRoles: ["student"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "gamification",
  },
  "profile.activity": {
    id: "profile.activity",
    name: "Recent Activity",
    description: "Timeline of recent learning activities",
    category: "profile",
    icon: "activity",
    allowedRoles: ["student", "teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
  },
  "notifications.recent": {
    id: "notifications.recent",
    name: "Recent Notifications",
    description: "Latest notifications",
    category: "notifications",
    icon: "bell",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "actions.quick": {
    id: "actions.quick",
    name: "Quick Actions",
    description: "Quick action buttons",
    category: "actions",
    icon: "zap",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
  },
  "hero.greeting": {
    id: "hero.greeting",
    name: "Hero Greeting",
    description: "Welcome card with user info",
    category: "profile",
    icon: "smile",
    allowedRoles: ["student", "teacher", "parent", "admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
  },

  // ============ TEACHER WIDGETS ============
  "analytics.class-performance": {
    id: "analytics.class-performance",
    name: "Class Performance",
    description: "Class-wide analytics",
    category: "analytics",
    icon: "bar-chart-2",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "analytics.attendance": {
    id: "analytics.attendance",
    name: "Attendance",
    description: "Attendance tracking",
    category: "analytics",
    icon: "check-square",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "class.roster": {
    id: "class.roster",
    name: "Class Roster",
    description: "Student list",
    category: "analytics",
    icon: "list",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "class.live-controls": {
    id: "class.live-controls",
    name: "Live Class Controls",
    description: "Controls for live class",
    category: "schedule",
    icon: "video",
    allowedRoles: ["teacher"],
    allowedScreenTypes: ["detail"],
    supportedSizes: ["standard"],
    defaultSize: "standard",
    requiredFeatureId: "live_classes",
  },

  // ============ PARENT WIDGETS ============
  "parent.children-overview": {
    id: "parent.children-overview",
    name: "Children Overview",
    description: "Cards for each child with quick stats and today's attendance",
    category: "profile",
    icon: "users",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.children",
  },
  "parent.attendance-summary": {
    id: "parent.attendance-summary",
    name: "Attendance Summary",
    description: "Track children's attendance with today's status, weekly and monthly stats",
    category: "analytics",
    icon: "check-square",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.attendance",
  },
  "parent.fee-alerts": {
    id: "parent.fee-alerts",
    name: "Fee Alerts",
    description: "Pending fees, overdue payments, and payment status for all children",
    category: "analytics",
    icon: "credit-card",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.fees",
  },
  "parent.notifications-preview": {
    id: "parent.notifications-preview",
    name: "Parent Notifications",
    description: "Recent notifications with unread count, category icons, and priority indicators",
    category: "notifications",
    icon: "bell",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.notifications",
  },
  "parent.ai-insights-preview": {
    id: "parent.ai-insights-preview",
    name: "Parent AI Insights",
    description: "AI-powered insights about child performance, attendance, and recommendations",
    category: "ai",
    icon: "brain",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.ai-insights",
  },
  "parent.quick-actions": {
    id: "parent.quick-actions",
    name: "Parent Quick Actions",
    description: "Common parent actions like pay fees, message teacher, view reports, and more",
    category: "actions",
    icon: "zap",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.quick-actions",
  },
  "parent.child-progress": {
    id: "parent.child-progress",
    name: "Child Progress Overview",
    description: "Overall academic progress summary with total completion percentage and study hours",
    category: "progress",
    icon: "trending-up",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.progress",
  },
  "parent.child-stats": {
    id: "parent.child-stats",
    name: "Child Stats",
    description: "Learning statistics grid with XP, streak, badges, study time, tests, and assignments",
    category: "progress",
    icon: "bar-chart-2",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.stats",
  },
  "parent.weak-areas": {
    id: "parent.weak-areas",
    name: "Child Weak Areas",
    description: "Topics needing attention with mastery percentage, difficulty, and practice recommendations",
    category: "progress",
    icon: "alert-triangle",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.progress",
  },
  "parent.performance-chart": {
    id: "parent.performance-chart",
    name: "Performance Chart",
    description: "Subject scores with bar charts and weekly XP progress visualization",
    category: "progress",
    icon: "bar-chart-2",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.progress",
  },
  "parent.assignments-pending": {
    id: "parent.assignments-pending",
    name: "Child Pending Assignments",
    description: "Assignments due soon with overdue alerts, due dates, and subject info",
    category: "assessment",
    icon: "clipboard-list",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.assignments",
  },
  "parent.subject-progress": {
    id: "parent.subject-progress",
    name: "Child Subject Progress",
    description: "Subject-wise academic progress with scores, chapters, and test stats",
    category: "progress",
    icon: "book-education",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.progress",
  },
  "parent.report-card-preview": {
    id: "parent.report-card-preview",
    name: "Child Report Card",
    description: "Academic grades summary with overall grade, subject grades, and pass rate",
    category: "progress",
    icon: "file-text",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.progress",
  },
  "parent.messages-inbox": {
    id: "parent.messages-inbox",
    name: "Parent Messages",
    description: "Inbox for messages from teachers and school with unread count and categories",
    category: "notifications",
    icon: "mail",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.messages",
  },
  "parent.announcements": {
    id: "parent.announcements",
    name: "School Announcements",
    description: "School announcements with pinned items, categories, and priority indicators",
    category: "notifications",
    icon: "megaphone",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.announcements",
  },
  "parent.teacher-contacts": {
    id: "parent.teacher-contacts",
    name: "Teacher Contacts",
    description: "Contact teachers with availability status, call, email, and message options",
    category: "social",
    icon: "users",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.teacher-contacts",
  },
  "parent.fee-summary": {
    id: "parent.fee-summary",
    name: "Fee Summary",
    description: "Complete fee overview with total due, overdue amounts, payment status, and pay buttons",
    category: "analytics",
    icon: "wallet",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.fees",
  },
  "parent.pending-fees": {
    id: "parent.pending-fees",
    name: "Pending Fees",
    description: "Fees due soon with urgency indicators, overdue alerts, and quick pay buttons",
    category: "analytics",
    icon: "clock",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.fees",
  },
  "parent.payment-history": {
    id: "parent.payment-history",
    name: "Payment History",
    description: "Record of completed payments with receipt numbers, payment methods, and totals",
    category: "analytics",
    icon: "history",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.fees",
  },
  "parent.ai-predictions": {
    id: "parent.ai-predictions",
    name: "AI Predictions",
    description: "AI-powered predictions and forecasts for child performance, attendance, and behavior",
    category: "ai",
    icon: "brain",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.ai-predictions",
  },
  "parent.ai-recommendations": {
    id: "parent.ai-recommendations",
    name: "AI Recommendations",
    description: "Personalized AI-powered suggestions for study, practice, resources, and activities",
    category: "ai",
    icon: "lightbulb",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.ai-recommendations",
  },
  "parent.ai-alerts": {
    id: "parent.ai-alerts",
    name: "AI Alerts",
    description: "Early warning system with severity-based alerts for academic, attendance, and behavior issues",
    category: "ai",
    icon: "bell-alert",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.ai-alerts",
  },
  "parent.comparison-analytics": {
    id: "parent.comparison-analytics",
    name: "Comparison Analytics",
    description: "Compare child's performance against class average, grade level, and historical data",
    category: "analytics",
    icon: "chart-bar",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "parent.analytics",
  },
  "child.schedule": {
    id: "child.schedule",
    name: "Child Schedule",
    description: "Child's class schedule",
    category: "schedule",
    icon: "calendar",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
  "child.attendance": {
    id: "child.attendance",
    name: "Child Attendance",
    description: "Child's attendance record",
    category: "analytics",
    icon: "check-square",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "child.selector": {
    id: "child.selector",
    name: "Child Selector",
    description: "Switch between children",
    category: "profile",
    icon: "users",
    allowedRoles: ["parent"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact"],
    defaultSize: "compact",
  },

  // ============ ADMIN WIDGETS ============
  "admin.hero-card": {
    id: "admin.hero-card",
    name: "Admin Hero Card",
    description: "Admin greeting with avatar, quick stats (users, revenue, alerts), and action buttons",
    category: "profile",
    icon: "user-cog",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.dashboard",
  },
  "admin.stats-grid": {
    id: "admin.stats-grid",
    name: "Admin Stats Grid",
    description: "4-stat grid showing total users, active users, revenue, and alerts with trends",
    category: "analytics",
    icon: "view-grid",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.dashboard",
  },
  "admin.system-health": {
    id: "admin.system-health",
    name: "System Health",
    description: "System health monitoring with uptime, CPU, memory usage, and active users with progress bars",
    category: "analytics",
    icon: "heart-pulse",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard", "expanded"],
    defaultSize: "standard",
    requiredFeatureId: "admin.dashboard",
  },
  "admin.stats": {
    id: "admin.stats",
    name: "Admin Stats",
    description: "Platform statistics",
    category: "analytics",
    icon: "activity",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "expanded",
  },
  "admin.users": {
    id: "admin.users",
    name: "User Management",
    description: "User overview",
    category: "analytics",
    icon: "users",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard", "hub"],
    supportedSizes: ["standard", "expanded"],
    defaultSize: "standard",
  },
  "admin.config": {
    id: "admin.config",
    name: "Config Status",
    description: "Configuration status",
    category: "analytics",
    icon: "settings",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "compact",
  },
  "admin.alerts": {
    id: "admin.alerts",
    name: "System Alerts",
    description: "System notifications",
    category: "notifications",
    icon: "alert-circle",
    allowedRoles: ["admin"],
    allowedScreenTypes: ["dashboard"],
    supportedSizes: ["compact", "standard"],
    defaultSize: "standard",
  },
};

// Helper functions
export function getWidget(widgetId: string): WidgetMetadata | undefined {
  return widgetRegistry[widgetId];
}

export function getWidgetsByCategory(category: WidgetCategory): WidgetMetadata[] {
  return Object.values(widgetRegistry).filter((w) => w.category === category);
}

export function getWidgetsForRole(role: string): WidgetMetadata[] {
  return Object.values(widgetRegistry).filter((w) =>
    w.allowedRoles.includes(role as any)
  );
}

export function getAllWidgets(): WidgetMetadata[] {
  return Object.values(widgetRegistry);
}

export const WIDGET_CATEGORIES: { id: WidgetCategory; label: string; icon: string }[] = [
  { id: "schedule", label: "Schedule", icon: "calendar" },
  { id: "study", label: "Study", icon: "book" },
  { id: "assessment", label: "Assessment", icon: "clipboard" },
  { id: "doubts", label: "Doubts", icon: "help-circle" },
  { id: "progress", label: "Progress", icon: "trending-up" },
  { id: "social", label: "Social", icon: "users" },
  { id: "ai", label: "AI", icon: "bot" },
  { id: "automation", label: "Automation", icon: "webhook" },
  { id: "profile", label: "Profile", icon: "user" },
  { id: "notifications", label: "Notifications", icon: "bell" },
  { id: "actions", label: "Actions", icon: "zap" },
  { id: "analytics", label: "Analytics", icon: "bar-chart" },
];
