import { HeroCardWidget } from "../components/widgets/dashboard/HeroCardWidget";
import { TodayScheduleWidget } from "../components/widgets/dashboard/TodayScheduleWidget";
import { QuickActionsWidget } from "../components/widgets/dashboard/QuickActionsWidget";
import { AssignmentsTestsWidget } from "../components/widgets/dashboard/AssignmentsTestsWidget";
import { DoubtsInboxWidget } from "../components/widgets/dashboard/DoubtsInboxWidget";
import { ProgressSnapshotWidget } from "../components/widgets/dashboard/ProgressSnapshotWidget";
import { RecommendationsWidget } from "../components/widgets/dashboard/RecommendationsWidget";
import { ClassFeedWidget } from "../components/widgets/dashboard/ClassFeedWidget";
import { PeersGroupsWidget } from "../components/widgets/dashboard/PeersGroupsWidget";
import { ProfileCardWidget } from "../components/widgets/profile/ProfileCardWidget";
import { ProfileQuickLinksWidget } from "../components/widgets/profile/ProfileQuickLinksWidget";
import { ProfileStatsWidget } from "../components/widgets/profile/ProfileStatsWidget";
import { ProfileAchievementsWidget } from "../components/widgets/profile/ProfileAchievementsWidget";
import { ProfileActivityWidget } from "../components/widgets/profile/ProfileActivityWidget";
import { SubjectProgressWidget } from "../components/widgets/progress/SubjectProgressWidget";
import { StudyStreakWidget } from "../components/widgets/progress/StudyStreakWidget";
import { LearningGoalsWidget } from "../components/widgets/progress/LearningGoalsWidget";
import { StatsGridWidget } from "../components/widgets/stats/StatsGridWidget";
import { ActiveQuestsWidget } from "../components/widgets/gamification/ActiveQuestsWidget";
import { PeersLeaderboardWidget } from "../components/widgets/social/PeersLeaderboardWidget";
import { ContinueLearningWidget } from "../components/widgets/study/ContinueLearningWidget";
import { WeakAreasWidget } from "../components/widgets/progress/WeakAreasWidget";
import { AnalyticsSnapshotWidget } from "../components/widgets/analytics/AnalyticsSnapshotWidget";
// Parent widgets
import { ChildrenOverviewWidget } from "../components/widgets/parent/ChildrenOverviewWidget";
import { AttendanceSummaryWidget } from "../components/widgets/parent/AttendanceSummaryWidget";
import { FeeAlertsWidget } from "../components/widgets/parent/FeeAlertsWidget";
import { NotificationsPreviewWidget } from "../components/widgets/parent/NotificationsPreviewWidget";
import { AIInsightsPreviewWidget } from "../components/widgets/parent/AIInsightsPreviewWidget";
import { ParentQuickActionsWidget } from "../components/widgets/parent/ParentQuickActionsWidget";
import { ChildProgressWidget } from "../components/widgets/parent/ChildProgressWidget";
import { ChildStatsWidget } from "../components/widgets/parent/ChildStatsWidget";
import { ChildWeakAreasWidget } from "../components/widgets/parent/ChildWeakAreasWidget";
import { ChildPerformanceChartWidget } from "../components/widgets/parent/ChildPerformanceChartWidget";
import { ChildAssignmentsWidget } from "../components/widgets/parent/ChildAssignmentsWidget";
import { ChildSubjectProgressWidget } from "../components/widgets/parent/ChildSubjectProgressWidget";
import { ChildReportCardWidget } from "../components/widgets/parent/ChildReportCardWidget";
import { SubjectGradesWidget } from "../components/widgets/parent/SubjectGradesWidget";
import { ReportCardSummaryWidget } from "../components/widgets/parent/ReportCardSummaryWidget";
import { TeacherRemarksWidget } from "../components/widgets/parent/TeacherRemarksWidget";
import { ParentMessagesWidget } from "../components/widgets/parent/ParentMessagesWidget";
import { ParentAnnouncementsWidget } from "../components/widgets/parent/ParentAnnouncementsWidget";
import { ParentTeacherContactsWidget } from "../components/widgets/parent/ParentTeacherContactsWidget";
import { ParentFeeSummaryWidget } from "../components/widgets/parent/ParentFeeSummaryWidget";
import { ParentPendingFeesWidget } from "../components/widgets/parent/ParentPendingFeesWidget";
import { ParentPaymentHistoryWidget } from "../components/widgets/parent/ParentPaymentHistoryWidget";
import { ParentAIPredictionsWidget } from "../components/widgets/parent/ParentAIPredictionsWidget";
import { ParentAIRecommendationsWidget } from "../components/widgets/parent/ParentAIRecommendationsWidget";
import { ParentAIAlertsWidget } from "../components/widgets/parent/ParentAIAlertsWidget";
import { ParentComparisonAnalyticsWidget } from "../components/widgets/parent/ParentComparisonAnalyticsWidget";
// AI widgets
import { AITutorChatWidget } from "../components/widgets/ai/AITutorChatWidget";
// Automation widgets
import { N8nTestWidget } from "../components/widgets/automation/N8nTestWidget";
import type { WidgetComponent, WidgetId, WidgetMetadata } from "../types/widget.types";

type WidgetRegistryEntry = {
  component: WidgetComponent;
  metadata: WidgetMetadata;
};

const registry: Record<WidgetId, WidgetRegistryEntry> = {
  // New short IDs (used in database)
  "hero.greeting": {
    component: HeroCardWidget,
    metadata: buildMetadata("hero.greeting", "dashboard:widgets.heroCard.title", "dashboard:widgets.heroCard.subtitle", "home.dashboard"),
  },
  "schedule.today": {
    component: TodayScheduleWidget,
    metadata: buildMetadata("schedule.today", "dashboard:widgets.todaySchedule.title", "dashboard:widgets.todaySchedule.subtitle", "home.dashboard"),
  },
  "actions.quick": {
    component: QuickActionsWidget,
    metadata: buildMetadata("actions.quick", "dashboard:widgets.quickActions.title", "dashboard:widgets.quickActions.subtitle", "home.dashboard"),
  },
  "assignments.pending": {
    component: AssignmentsTestsWidget,
    metadata: buildMetadata("assignments.pending", "dashboard:widgets.assignmentsTests.title", "dashboard:widgets.assignmentsTests.subtitle", "study.assignments"),
  },
  "doubts.inbox": {
    component: DoubtsInboxWidget,
    metadata: buildMetadata("doubts.inbox", "dashboard:widgets.doubtsInbox.title", "dashboard:widgets.doubtsInbox.subtitle", "ask.doubts"),
  },
  "progress.snapshot": {
    component: ProgressSnapshotWidget,
    metadata: buildMetadata("progress.snapshot", "dashboard:widgets.progressSnapshot.title", "dashboard:widgets.progressSnapshot.subtitle", "progress.analytics"),
  },
  "progress.subject-wise": {
    component: SubjectProgressWidget,
    metadata: {
      id: "progress.subject-wise",
      titleKey: "dashboard:widgets.subjectProgress.title",
      descriptionKey: "dashboard:widgets.subjectProgress.subtitle",
      featureId: "progress.analytics",
      roles: ["student", "parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxSubjects: 5,
        showChapters: true,
        showStats: true,
        showProgressBar: true,
        showPercentage: true,
        showLastActivity: false,
        sortBy: "progress",
        enableTap: true,
        showViewAll: true,
      },
      requiredPermissions: [],
    },
  },
  "progress.streak": {
    component: StudyStreakWidget,
    metadata: {
      id: "progress.streak",
      titleKey: "dashboard:widgets.studyStreak.title",
      descriptionKey: "dashboard:widgets.studyStreak.subtitle",
      featureId: "progress.analytics",
      roles: ["student", "parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        showCurrentStreak: true,
        showLongestStreak: true,
        showWeeklyGoal: true,
        showAchievements: true,
        showRecentActivity: false,
        maxAchievements: 2,
        enableTap: true,
        showMotivation: true,
      },
      requiredPermissions: [],
    },
  },
  "progress.goals": {
    component: LearningGoalsWidget,
    metadata: {
      id: "progress.goals",
      titleKey: "dashboard:widgets.learningGoals.title",
      descriptionKey: "dashboard:widgets.learningGoals.subtitle",
      featureId: "progress.analytics",
      roles: ["student"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        maxGoals: 4,
        showProgress: true,
        showDeadline: true,
        showPriority: true,
        showAddButton: true,
        compactMode: false,
        enableTap: true,
      },
    },
  },
  "progress.weak-areas": {
    component: WeakAreasWidget,
    metadata: {
      id: "progress.weak-areas",
      titleKey: "dashboard:widgets.weakAreas.title",
      descriptionKey: "dashboard:widgets.weakAreas.subtitle",
      featureId: "progress.analytics",
      roles: ["student", "parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        maxTopics: 4,
        showScore: true,
        showPracticeButton: true,
        showDifficulty: true,
        showSubject: true,
        showChapter: false,
        sortBy: "score",
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "stats.grid": {
    component: StatsGridWidget,
    metadata: {
      id: "stats.grid",
      titleKey: "dashboard:widgets.statsGrid.title",
      descriptionKey: "dashboard:widgets.statsGrid.subtitle",
      featureId: "progress.analytics",
      roles: ["student", "parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        columns: 2,
        showXP: true,
        showStreak: true,
        showBadges: true,
        showStudyTime: true,
        showTests: true,
        showAssignments: true,
        showTrends: true,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "analytics.snapshot": {
    component: AnalyticsSnapshotWidget,
    metadata: {
      id: "analytics.snapshot",
      titleKey: "dashboard:widgets.analyticsSnapshot.title",
      descriptionKey: "dashboard:widgets.analyticsSnapshot.subtitle",
      featureId: "progress.analytics",
      roles: ["student", "parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 3,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        showThisWeek: true,
        showSubjects: true,
        showStreak: true,
        showTrends: true,
        showRecommendations: true,
        maxSubjects: 3,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "quests.active": {
    component: ActiveQuestsWidget,
    metadata: {
      id: "quests.active",
      titleKey: "dashboard:widgets.activeQuests.title",
      descriptionKey: "dashboard:widgets.activeQuests.subtitle",
      featureId: "gamification",
      roles: ["student"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 2 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        maxQuests: 3,
        showDaily: true,
        showWeekly: true,
        showProgress: true,
        showXPReward: true,
        showSummary: true,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "ai.recommendations": {
    component: RecommendationsWidget,
    metadata: buildMetadata("ai.recommendations", "dashboard:widgets.recommendations.title", "dashboard:widgets.recommendations.subtitle", "ai.tutor", ["ai.tutor.use"]),
  },
  "ai.tutor-chat": {
    component: AITutorChatWidget,
    metadata: {
      id: "ai.tutor-chat",
      titleKey: "dashboard:widgets.aiTutor.title",
      descriptionKey: "dashboard:widgets.aiTutor.subtitle",
      featureId: "ai.tutor",
      roles: ["student"],
      requiresOnline: true,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["standard", "expanded"],
      defaultSize: "expanded",
      minHeight: "lg",
      dataPolicy: {
        maxQueries: 0,
        staleTimeMs: 0,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: false,
      },
      defaultConfig: {
        showSettings: true,
        maxMessages: 50,
        enableVoice: false,
      },
      requiredPermissions: ["ai.tutor.use"],
    },
  },
  // ============ AUTOMATION WIDGETS ============
  "automation.n8n-test": {
    component: N8nTestWidget,
    metadata: {
      id: "automation.n8n-test",
      titleKey: "dashboard:widgets.n8nTest.title",
      descriptionKey: "dashboard:widgets.n8nTest.subtitle",
      featureId: "automation",
      roles: ["student", "teacher", "parent", "admin"],
      requiresOnline: true,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["standard", "expanded"],
      defaultSize: "standard",
      minHeight: "md",
      dataPolicy: {
        maxQueries: 0,
        staleTimeMs: 0,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: false,
      },
      defaultConfig: {
        webhookUrl: "",
        showResponse: true,
        enableCustomMessage: true,
      },
      requiredPermissions: [],
    },
  },
  "peers.leaderboard": {
    component: PeersLeaderboardWidget,
    metadata: {
      id: "peers.leaderboard",
      titleKey: "dashboard:widgets.peersLeaderboard.title",
      descriptionKey: "dashboard:widgets.peersLeaderboard.subtitle",
      featureId: "peers.network",
      roles: ["student"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        scope: "school",
        maxEntries: 5,
        showMyRank: true,
        showPercentile: true,
        showScope: true,
        showXP: true,
        showStreak: true,
        compactMode: false,
        enableTap: true,
      },
    },
  },
  "continue.learning": {
    component: ContinueLearningWidget,
    metadata: {
      id: "continue.learning",
      titleKey: "dashboard:widgets.continueLearning.title",
      descriptionKey: "dashboard:widgets.continueLearning.subtitle",
      featureId: "home.dashboard",
      roles: ["student"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 2 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        maxItems: 4,
        showProgress: true,
        showTimeAgo: true,
        showType: true,
        layoutStyle: "horizontal",
        enableTap: true,
        compactMode: false,
      },
      requiredPermissions: [],
    },
  },
  "feed.class": {
    component: ClassFeedWidget,
    metadata: buildMetadata("feed.class", "dashboard:widgets.classFeed.title", "dashboard:widgets.classFeed.subtitle", "home.dashboard"),
  },
  "peers.groups": {
    component: PeersGroupsWidget,
    metadata: buildMetadata("peers.groups", "dashboard:widgets.peersGroups.title", "dashboard:widgets.peersGroups.subtitle", "peers.network"),
  },
  // Profile widgets
  "profile.card": {
    component: ProfileCardWidget,
    metadata: {
      id: "profile.card",
      titleKey: "profile:widgets.profileCard.title",
      descriptionKey: "profile:widgets.profileCard.subtitle",
      featureId: "profile",
      roles: ["student", "teacher", "parent", "admin"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        showAvatar: true,
        showClass: true,
        showSchool: true,
        showStats: true,
        showEditButton: true,
        avatarSize: "medium",
        layoutStyle: "horizontal",
      },
      requiredPermissions: [],
    },
  },

  "profile.quickLinks": {
    component: ProfileQuickLinksWidget,
    metadata: {
      id: "profile.quickLinks",
      titleKey: "profile:widgets.quickLinks.title",
      descriptionKey: "profile:widgets.quickLinks.subtitle",
      featureId: "profile",
      roles: ["student", "teacher", "parent", "admin"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 0,
        staleTimeMs: 0,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: false,
      },
      defaultConfig: {
        showEditProfile: true,
        showSettings: true,
        showNotifications: true,
        showHelp: true,
        showAbout: true,
        showLogout: true,
        layoutStyle: "list",
        showIcons: true,
        showDividers: true,
      },
      requiredPermissions: [],
    },
  },
  "profile.stats": {
    component: ProfileStatsWidget,
    metadata: {
      id: "profile.stats",
      titleKey: "profile:widgets.profileStats.title",
      descriptionKey: "profile:widgets.profileStats.subtitle",
      featureId: "profile",
      roles: ["student", "teacher"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "grid",
        showXP: true,
        showStreak: true,
        showBadges: true,
        showStudyTime: true,
        showAssessments: true,
        showProgress: true,
        showTrends: true,
        compactMode: false,
      },
      requiredPermissions: [],
    },
  },
  "profile.achievements": {
    component: ProfileAchievementsWidget,
    metadata: {
      id: "profile.achievements",
      titleKey: "profile:widgets.achievements.title",
      descriptionKey: "profile:widgets.achievements.subtitle",
      featureId: "gamification",
      roles: ["student"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "grid",
        maxItems: 6,
        showProgress: true,
        showPoints: true,
        showRarity: true,
        showLocked: true,
        showSummary: true,
        filterCategory: "all",
      },
      requiredPermissions: [],
    },
  },
  "profile.activity": {
    component: ProfileActivityWidget,
    metadata: {
      id: "profile.activity",
      titleKey: "profile:widgets.activity.title",
      descriptionKey: "profile:widgets.activity.subtitle",
      featureId: "profile",
      roles: ["student", "teacher"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 2 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "timeline",
        maxItems: 10,
        showTodayStats: true,
        showPoints: true,
        showTime: true,
        showGroupHeaders: true,
        compactMode: false,
      },
      requiredPermissions: [],
    },
  },
  // ============ PARENT WIDGETS ============
  "parent.children-overview": {
    component: ChildrenOverviewWidget,
    metadata: {
      id: "parent.children-overview",
      titleKey: "parent:widgets.childrenOverview.title",
      descriptionKey: "parent:widgets.childrenOverview.subtitle",
      featureId: "parent.children",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "cards",
        showAvatar: true,
        showClass: true,
        showAttendanceToday: true,
        showQuickStats: true,
        statsToShow: ["attendance", "assignments", "streak"],
        enableTap: true,
        showViewAll: false,
      },
      requiredPermissions: [], // No permissions required for now
    },
  },
  "parent.attendance-summary": {
    component: AttendanceSummaryWidget,
    metadata: {
      id: "parent.attendance-summary",
      titleKey: "parent:widgets.attendanceSummary.title",
      descriptionKey: "parent:widgets.attendanceSummary.subtitle",
      featureId: "parent.attendance",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "cards",
        showTodayStatus: true,
        showWeekSummary: true,
        showMonthStats: true,
        showPercentage: true,
        showCheckInTime: false,
        showRecentDays: false,
        maxRecentDays: 5,
        enableTap: true,
        showViewAll: false,
      },
      requiredPermissions: [],
    },
  },
  "parent.fee-alerts": {
    component: FeeAlertsWidget,
    metadata: {
      id: "parent.fee-alerts",
      titleKey: "parent:widgets.feeAlerts.title",
      descriptionKey: "parent:widgets.feeAlerts.subtitle",
      featureId: "parent.fees",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        showOverdueFirst: true,
        showAmount: true,
        showDueDate: true,
        showFeeType: true,
        showPayButton: true,
        maxItems: 5,
        enableTap: true,
        showTotalSummary: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.notifications-preview": {
    component: NotificationsPreviewWidget,
    metadata: {
      id: "parent.notifications-preview",
      titleKey: "parent:widgets.notificationsPreview.title",
      descriptionKey: "parent:widgets.notificationsPreview.subtitle",
      featureId: "parent.notifications",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 2 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 5,
        showUnreadBadge: true,
        showCategory: true,
        showTime: true,
        showPriority: true,
        showPreview: true,
        enableTap: true,
        showUnreadFirst: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.ai-insights-preview": {
    component: AIInsightsPreviewWidget,
    metadata: {
      id: "parent.ai-insights-preview",
      titleKey: "parent:widgets.aiInsights.title",
      descriptionKey: "parent:widgets.aiInsights.subtitle",
      featureId: "parent.ai-insights",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 4,
        showHighPriorityFirst: true,
        showDescription: true,
        showActionButton: true,
        showCategory: true,
        showUnreadBadge: true,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.quick-actions": {
    component: ParentQuickActionsWidget,
    metadata: {
      id: "parent.quick-actions",
      titleKey: "parent:widgets.quickActions.title",
      descriptionKey: "parent:widgets.quickActions.subtitle",
      featureId: "parent.quick-actions",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 10 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        columns: 2,
        showLabels: true,
        iconSize: "medium",
        style: "filled",
        maxActions: 6,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.child-progress": {
    component: ChildProgressWidget,
    metadata: {
      id: "parent.child-progress",
      titleKey: "parent:widgets.childProgress.title",
      descriptionKey: "parent:widgets.childProgress.subtitle",
      featureId: "parent.progress",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxSubjects: 4,
        showOverallProgress: true,
        showHoursStudied: true,
        showTestStats: true,
        showProgressBar: true,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.child-stats": {
    component: ChildStatsWidget,
    metadata: {
      id: "parent.child-stats",
      titleKey: "parent:widgets.childStats.title",
      descriptionKey: "parent:widgets.childStats.subtitle",
      featureId: "parent.stats",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "grid",
        columns: 2,
        showXP: true,
        showStreak: true,
        showBadges: true,
        showStudyTime: true,
        showTests: true,
        showAssignments: true,
        showTrends: true,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.weak-areas": {
    component: ChildWeakAreasWidget,
    metadata: {
      id: "parent.weak-areas",
      titleKey: "parent:widgets.weakAreas.title",
      descriptionKey: "parent:widgets.weakAreas.subtitle",
      featureId: "parent.progress",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxTopics: 4,
        showScore: true,
        showPracticeButton: true,
        showDifficulty: true,
        showSubject: true,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.performance-chart": {
    component: ChildPerformanceChartWidget,
    metadata: {
      id: "parent.performance-chart",
      titleKey: "parent:widgets.performanceChart.title",
      descriptionKey: "parent:widgets.performanceChart.subtitle",
      featureId: "parent.progress",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "stacked",
        chartType: "bar",
        showSubjectScores: true,
        showWeeklyProgress: true,
        showAverageScore: true,
        showBestScore: true,
        maxSubjects: 5,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.assignments-pending": {
    component: ChildAssignmentsWidget,
    metadata: {
      id: "parent.assignments-pending",
      titleKey: "parent:widgets.assignmentsPending.title",
      descriptionKey: "parent:widgets.assignmentsPending.subtitle",
      featureId: "parent.assignments",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 5,
        showSubject: true,
        showDueDate: true,
        showPoints: true,
        showType: true,
        showOverdueBadge: true,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.subject-progress": {
    component: ChildSubjectProgressWidget,
    metadata: {
      id: "parent.subject-progress",
      titleKey: "parent:widgets.subjectProgress.title",
      descriptionKey: "parent:widgets.subjectProgress.subtitle",
      featureId: "parent.progress",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxSubjects: 5,
        showProgressBar: true,
        showScore: true,
        showChapters: true,
        showTests: true,
        showOverallProgress: true,
        showStudyHours: true,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.report-card-preview": {
    component: ChildReportCardWidget,
    metadata: {
      id: "parent.report-card-preview",
      titleKey: "parent:widgets.reportCardPreview.title",
      descriptionKey: "parent:widgets.reportCardPreview.subtitle",
      featureId: "parent.progress",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxSubjects: 5,
        showOverallGrade: true,
        showAverageScore: true,
        showBestScore: true,
        showPassRate: true,
        showTerm: true,
        showSubjectGrades: true,
        showGradePoints: true,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.subject-grades": {
    component: SubjectGradesWidget,
    metadata: {
      id: "parent.subject-grades",
      titleKey: "parent:widgets.subjectGrades.title",
      descriptionKey: "parent:widgets.subjectGrades.subtitle",
      featureId: "parent.progress",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["standard", "expanded"],
      defaultSize: "expanded",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {},
      requiredPermissions: [],
    },
  },
  "parent.report-card-summary": {
    component: ReportCardSummaryWidget,
    metadata: {
      id: "parent.report-card-summary",
      titleKey: "parent:widgets.reportCardSummary.title",
      descriptionKey: "parent:widgets.reportCardSummary.subtitle",
      featureId: "parent.progress",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["standard", "expanded"],
      defaultSize: "expanded",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {},
      requiredPermissions: [],
    },
  },
  "parent.teacher-remarks": {
    component: TeacherRemarksWidget,
    metadata: {
      id: "parent.teacher-remarks",
      titleKey: "parent:widgets.teacherRemarks.title",
      descriptionKey: "parent:widgets.teacherRemarks.subtitle",
      featureId: "parent.progress",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: false,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {},
      requiredPermissions: [],
    },
  },
  "parent.messages-inbox": {
    component: ParentMessagesWidget,
    metadata: {
      id: "parent.messages-inbox",
      titleKey: "parent:widgets.messagesInbox.title",
      descriptionKey: "parent:widgets.messagesInbox.subtitle",
      featureId: "parent.messages",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 2 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 5,
        showUnreadBadge: true,
        showCategory: true,
        showTime: true,
        showPriority: true,
        showPreview: true,
        showUnreadFirst: true,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.announcements": {
    component: ParentAnnouncementsWidget,
    metadata: {
      id: "parent.announcements",
      titleKey: "parent:widgets.announcements.title",
      descriptionKey: "parent:widgets.announcements.subtitle",
      featureId: "parent.announcements",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 5,
        showPinnedFirst: true,
        showPinnedBadge: true,
        showCategory: true,
        showTime: true,
        showPriority: true,
        showPreview: true,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.teacher-contacts": {
    component: ParentTeacherContactsWidget,
    metadata: {
      id: "parent.teacher-contacts",
      titleKey: "parent:widgets.teacherContacts.title",
      descriptionKey: "parent:widgets.teacherContacts.subtitle",
      featureId: "parent.teacher-contacts",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 1,
        staleTimeMs: 10 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 5,
        showClassTeacherFirst: true,
        showAvailability: true,
        showSubject: true,
        showContactButtons: true,
        showOfficeHours: false,
        compactMode: false,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.fee-summary": {
    component: ParentFeeSummaryWidget,
    metadata: {
      id: "parent.fee-summary",
      titleKey: "parent:widgets.feeSummary.title",
      descriptionKey: "parent:widgets.feeSummary.subtitle",
      featureId: "parent.fees",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 5,
        showTotalSummary: true,
        showDueDate: true,
        showFeeType: true,
        showAmount: true,
        showPayButton: true,
        showOverdueFirst: true,
        showProgressBar: true,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.pending-fees": {
    component: ParentPendingFeesWidget,
    metadata: {
      id: "parent.pending-fees",
      titleKey: "parent:widgets.pendingFees.title",
      descriptionKey: "parent:widgets.pendingFees.subtitle",
      featureId: "parent.fees",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 4,
        showDueDate: true,
        showFeeType: true,
        showAmount: true,
        showPayButton: true,
        showOverdueCount: true,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.payment-history": {
    component: ParentPaymentHistoryWidget,
    metadata: {
      id: "parent.payment-history",
      titleKey: "parent:widgets.paymentHistory.title",
      descriptionKey: "parent:widgets.paymentHistory.subtitle",
      featureId: "parent.fees",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 5,
        showPaymentMethod: true,
        showReceiptNumber: true,
        showAmount: true,
        showTotalSummary: true,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.ai-predictions": {
    component: ParentAIPredictionsWidget,
    metadata: {
      id: "parent.ai-predictions",
      titleKey: "parent:widgets.aiPredictions.title",
      descriptionKey: "parent:widgets.aiPredictions.subtitle",
      featureId: "parent.ai-predictions",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 4,
        showConfidence: true,
        showRecommendation: true,
        showPriority: true,
        showUnreadFirst: true,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.ai-recommendations": {
    component: ParentAIRecommendationsWidget,
    metadata: {
      id: "parent.ai-recommendations",
      titleKey: "parent:widgets.aiRecommendations.title",
      descriptionKey: "parent:widgets.aiRecommendations.subtitle",
      featureId: "parent.ai-recommendations",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 4,
        showDescription: true,
        showActionButton: true,
        showPriority: true,
        showRelevance: true,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.ai-alerts": {
    component: ParentAIAlertsWidget,
    metadata: {
      id: "parent.ai-alerts",
      titleKey: "parent:widgets.aiAlerts.title",
      descriptionKey: "parent:widgets.aiAlerts.subtitle",
      featureId: "parent.ai-alerts",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 2 * 60 * 1000, // 2 minutes - alerts refresh more frequently
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 4,
        showDescription: true,
        showActionRequired: true,
        showSeverity: true,
        showCriticalFirst: true,
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  "parent.comparison-analytics": {
    component: ParentComparisonAnalyticsWidget,
    metadata: {
      id: "parent.comparison-analytics",
      titleKey: "parent:widgets.comparisonAnalytics.title",
      descriptionKey: "parent:widgets.comparisonAnalytics.subtitle",
      featureId: "parent.analytics",
      roles: ["parent"],
      requiresOnline: false,
      deprecated: false,
      version: "1.0.0",
      supportedSizes: ["compact", "standard", "expanded"],
      defaultSize: "standard",
      dataPolicy: {
        maxQueries: 2,
        staleTimeMs: 5 * 60 * 1000,
        prefetchOnDashboardLoad: true,
        allowBackgroundRefresh: true,
      },
      defaultConfig: {
        layoutStyle: "list",
        maxItems: 5,
        showInsights: true,
        showTrend: true,
        showPercentile: true,
        showComparisonBar: true,
        comparisonType: "class_average",
        enableTap: true,
      },
      requiredPermissions: [],
    },
  },
  // Legacy long IDs (for backward compatibility)
  "home.dashboard.heroCard": {
    component: HeroCardWidget,
    metadata: buildMetadata("home.dashboard.heroCard", "dashboard:widgets.heroCard.title", "dashboard:widgets.heroCard.subtitle", "home.dashboard"),
  },
  "home.dashboard.todaySchedule": {
    component: TodayScheduleWidget,
    metadata: buildMetadata("home.dashboard.todaySchedule", "dashboard:widgets.todaySchedule.title", "dashboard:widgets.todaySchedule.subtitle", "home.dashboard"),
  },
  "home.dashboard.quickActions": {
    component: QuickActionsWidget,
    metadata: buildMetadata("home.dashboard.quickActions", "dashboard:widgets.quickActions.title", "dashboard:widgets.quickActions.subtitle", "home.dashboard"),
  },
  "home.dashboard.assignmentsTests": {
    component: AssignmentsTestsWidget,
    metadata: buildMetadata("home.dashboard.assignmentsTests", "dashboard:widgets.assignmentsTests.title", "dashboard:widgets.assignmentsTests.subtitle", "study.assignments"),
  },
  "home.dashboard.doubtsInbox": {
    component: DoubtsInboxWidget,
    metadata: buildMetadata("home.dashboard.doubtsInbox", "dashboard:widgets.doubtsInbox.title", "dashboard:widgets.doubtsInbox.subtitle", "ask.doubts"),
  },
  "home.dashboard.progressSnapshot": {
    component: ProgressSnapshotWidget,
    metadata: buildMetadata("home.dashboard.progressSnapshot", "dashboard:widgets.progressSnapshot.title", "dashboard:widgets.progressSnapshot.subtitle", "progress.analytics"),
  },
  "home.dashboard.recommendations": {
    component: RecommendationsWidget,
    metadata: buildMetadata("home.dashboard.recommendations", "dashboard:widgets.recommendations.title", "dashboard:widgets.recommendations.subtitle", "ai.tutor", ["ai.tutor.use"]),
  },
  "home.dashboard.classFeed": {
    component: ClassFeedWidget,
    metadata: buildMetadata("home.dashboard.classFeed", "dashboard:widgets.classFeed.title", "dashboard:widgets.classFeed.subtitle", "home.dashboard"),
  },
  "home.dashboard.peersGroups": {
    component: PeersGroupsWidget,
    metadata: buildMetadata("home.dashboard.peersGroups", "dashboard:widgets.peersGroups.title", "dashboard:widgets.peersGroups.subtitle", "peers.network"),
  },
};

export function getWidgetRegistry() {
  return registry;
}

export function getWidgetEntry(widgetId: WidgetId): WidgetRegistryEntry | undefined {
  return registry[widgetId];
}

function buildMetadata(
  id: WidgetId,
  titleKey: string,
  descriptionKey: string,
  featureId: string,
  requiredPermissions: string[] = []
): WidgetMetadata {
  return {
    id,
    titleKey,
    descriptionKey,
    featureId,
    roles: ["student", "teacher", "parent", "admin"], // Allow all roles by default
    requiresOnline: false, // Don't require online by default
    deprecated: false,
    version: "1.0.0",
    dataPolicy: {
      maxQueries: 2,
      staleTimeMs: 5 * 60 * 1000,
      prefetchOnDashboardLoad: true,
      allowBackgroundRefresh: true,
    },
    defaultConfig: {},
    requiredPermissions: [], // Don't require permissions by default
  };
}
