export { useTeacherDashboardQuery } from './useTeacherDashboardQuery';
export type { TeacherDashboardStats } from './useTeacherDashboardQuery';
export { useTeacherClassesQuery } from './useTeacherClassesQuery';
export type { TeacherClass } from './useTeacherClassesQuery';
export { useTeacherScheduleQuery } from './useTeacherScheduleQuery';
export type { TeacherScheduleEntry } from './useTeacherScheduleQuery';
export { usePendingGradingQuery } from './usePendingGradingQuery';
export type { PendingGradingItem } from './usePendingGradingQuery';
export { useAtRiskStudentsQuery } from './useAtRiskStudentsQuery';
export type { AtRiskStudent } from './useAtRiskStudentsQuery';
export { useTeacherQuickActionsQuery } from './useTeacherQuickActionsQuery';
export type { TeacherQuickAction } from './useTeacherQuickActionsQuery';
export { useClassRosterQuery } from './useClassRosterQuery';
export type { ClassStudent } from './useClassRosterQuery';
export { useClassStatsQuery } from './useClassStatsQuery';
export type { ClassStats } from './useClassStatsQuery';
export { useClassOverviewQuery } from './useClassOverviewQuery';
export type { ClassOverviewItem, AtRiskStudent as ClassAtRiskStudent } from './useClassOverviewQuery';
export { useClassRecentActivityQuery, getRelativeTime, ACTIVITY_TYPE_CONFIG } from './useClassRecentActivityQuery';
export type { ClassActivity, ActivityType } from './useClassRecentActivityQuery';
export { useClassAttendanceQuery, getAttendanceSummary } from './useAttendanceQuery';
export type { StudentAttendance, AttendanceStatus, AttendanceRecord } from './useAttendanceQuery';
export { useAttendanceStatsQuery } from './useAttendanceStatsQuery';
export type { AttendanceStats } from './useAttendanceStatsQuery';
export { useRecentAttendanceQuery, getRelativeTime as getAttendanceRelativeTime } from './useRecentAttendanceQuery';
export type { RecentAttendanceRecord } from './useRecentAttendanceQuery';
export { useAttendanceReportsQuery } from './useAttendanceReportsQuery';
export type { AttendanceTrendPoint, ClassAttendanceData, LowAttendanceStudent, AttendanceReportsData } from './useAttendanceReportsQuery';
export { usePendingClassesQuery } from './usePendingClassesQuery';
export type { PendingClass } from './usePendingClassesQuery';
export { useAttendanceRecordsQuery, useAttendanceByDateQuery, useStudentAttendanceSummaryQuery } from './useAttendanceRecordsQuery';
export type { AttendanceRecord as AttendanceRecordFull, AttendanceRecordsQueryOptions } from './useAttendanceRecordsQuery';
export { useTeacherAssignmentsQuery, usePendingAssignmentsQuery, useAssignmentDetailQuery, useUpcomingAssignmentsQuery } from './useTeacherAssignmentsQuery';
export type { Assignment, AssignmentType, AssignmentStatus, TeacherAssignmentsQueryOptions } from './useTeacherAssignmentsQuery';
export { useSubmissionDetailQuery } from './useSubmissionDetailQuery';
export type { SubmissionDetail } from './useSubmissionDetailQuery';
export { useRecentGradingQuery } from './useRecentGradingQuery';
export type { RecentGradingItem } from './useRecentGradingQuery';
export { useGradingStatsQuery } from './useGradingStatsQuery';
export type { GradingStats } from './useGradingStatsQuery';
export { useRubricTemplatesQuery } from './useRubricTemplatesQuery';
export type { RubricTemplate } from './useRubricTemplatesQuery';
export { useTeacherMessagesQuery, useUnreadMessagesCount } from './useTeacherMessagesQuery';
export type { TeacherMessage } from './useTeacherMessagesQuery';
export { useTeacherAnnouncementsQuery } from './useTeacherAnnouncementsQuery';
export type { TeacherAnnouncement } from './useTeacherAnnouncementsQuery';
export { useParentContactsQuery } from './useParentContactsQuery';
export type { ParentContact } from './useParentContactsQuery';
export { useTeacherDoubtsQuery, useDoubtDetailQuery, usePendingDoubtsCount } from './useTeacherDoubtsQuery';
export type { TeacherDoubt } from './useTeacherDoubtsQuery';
export { useTeacherCalendarQuery, useTodayEventsQuery, useUpcomingEventsQuery } from './useTeacherCalendarQuery';
export type { TeacherCalendarEvent } from './useTeacherCalendarQuery';
export { useAiInsightsQuery, useUnreadInsightsCount, useHighPriorityInsightsQuery, INSIGHT_TYPE_CONFIG, PRIORITY_CONFIG } from './useAiInsightsQuery';
export type { AiInsight, InsightType, InsightPriority, InsightStatus, UseAiInsightsQueryOptions } from './useAiInsightsQuery';
